import type { Article } from "./content";
export const additionalArticles: Article[] = [
  {
    slug: "chapter-1-summary",
    title: "电路模型与基本定律全览",
    category: "电路基础",
    folder: "reviews",
    description: "按教材顺序串起本章8节：概念、条件、公式、数值代入与易错点。",
    keywords: [
      "第1章",
      "全览",
      "教材目录",
      "电路和电路模型",
      "电流和电压的参考方向",
      "电功率和能量",
      "电路元件",
      "电阻元件",
      "电压源和电流源",
      "受控电源",
      "基尔霍夫定律",
    ],
    core: true,
    readTime: "15–25",
  },
  {
    slug: "chapter-2-summary",
    title: "等效变换全览",
    category: "电路基础",
    folder: "reviews",
    description: "按教材顺序串起本章7节：概念、条件、公式、数值代入与易错点。",
    keywords: [
      "第2章",
      "全览",
      "教材目录",
      "引言",
      "电路的等效变换",
      "电阻的串联和并联",
      "电阻的Y形联结和Δ形联结的等效变换",
      "电压源、电流源的串联和并联",
      "实际电源的两种模型及其等效变换",
      "输入电阻",
    ],
    core: true,
    readTime: "15–25",
  },
  {
    slug: "chapter-3-summary",
    title: "电阻网络分析方法全览",
    category: "电路基础",
    folder: "reviews",
    description: "按教材顺序串起本章6节：概念、条件、公式、数值代入与易错点。",
    keywords: [
      "第3章",
      "全览",
      "教材目录",
      "电路的图",
      "KCL和KVL的独立方程数",
      "支路电流法",
      "网孔电流法",
      "回路电流法",
      "结点电压法",
    ],
    core: true,
    readTime: "15–25",
  },
  {
    slug: "chapter-4-summary",
    title: "电路定理全览",
    category: "电路基础",
    folder: "reviews",
    description: "按教材顺序串起本章4节：概念、条件、公式、数值代入与易错点。",
    keywords: [
      "第4章",
      "全览",
      "教材目录",
      "叠加定理",
      "替代定理",
      "戴维宁定理和诺顿定理",
      "最大功率传输定理",
    ],
    core: true,
    readTime: "15–25",
  },
  {
    slug: "chapter-6-summary",
    title: "储能元件全览",
    category: "动态电路",
    folder: "reviews",
    description: "按教材顺序串起本章3节：概念、条件、公式、数值代入与易错点。",
    keywords: [
      "第6章",
      "全览",
      "教材目录",
      "电容元件",
      "电感元件",
      "电容、电感元件的串联与并联",
    ],
    core: true,
    readTime: "15–25",
  },
  {
    slug: "chapter-7-summary",
    title: "一阶电路全览",
    category: "动态电路",
    folder: "reviews",
    description: "按教材顺序串起本章4节：概念、条件、公式、数值代入与易错点。",
    keywords: [
      "第7章",
      "全览",
      "教材目录",
      "动态电路的方程及其初始条件",
      "一阶电路的零输入响应",
      "一阶电路的零状态响应",
      "一阶电路的全响应",
    ],
    core: true,
    readTime: "15–25",
  },
  {
    slug: "chapter-8-summary",
    title: "复数与相量法全览",
    category: "正弦稳态",
    folder: "reviews",
    description: "按教材顺序串起本章4节：概念、条件、公式、数值代入与易错点。",
    keywords: [
      "第8章",
      "全览",
      "教材目录",
      "复数",
      "正弦量",
      "相量法的基础",
      "电路定律的相量形式",
    ],
    core: true,
    readTime: "15–25",
  },
  {
    slug: "chapter-9-summary",
    title: "正弦稳态分析全览",
    category: "正弦稳态",
    folder: "reviews",
    description: "按教材顺序串起本章6节：概念、条件、公式、数值代入与易错点。",
    keywords: [
      "第9章",
      "全览",
      "教材目录",
      "阻抗和导纳",
      "电路的相量图",
      "正弦稳态电路的分析",
      "正弦稳态电路的功率",
      "复功率",
      "最大功率传输",
    ],
    core: true,
    readTime: "15–25",
  },
  {
    slug: "chapter-10-summary",
    title: "耦合电感与理想变压器全览",
    category: "正弦稳态",
    folder: "reviews",
    description: "按教材顺序串起本章4节：概念、条件、公式、数值代入与易错点。",
    keywords: [
      "第10章",
      "全览",
      "教材目录",
      "互感",
      "含有耦合电感电路的计算",
      "耦合电感的功率",
      "理想变压器",
    ],
    core: true,
    readTime: "15–25",
  },
  {
    slug: "chapter-11-summary",
    title: "串联与并联谐振全览",
    category: "正弦稳态",
    folder: "reviews",
    description: "按教材顺序串起本章2节：概念、条件、公式、数值代入与易错点。",
    keywords: [
      "第11章",
      "全览",
      "教材目录",
      "RLC串联电路的谐振",
      "RLC并联谐振电路",
    ],
    core: true,
    readTime: "15–25",
  },
  {
    slug: "chapter-12-summary",
    title: "三相Y与Δ全览",
    category: "三相电路",
    folder: "reviews",
    description: "按教材顺序串起本章5节：概念、条件、公式、数值代入与易错点。",
    keywords: [
      "第12章",
      "全览",
      "教材目录",
      "三相电路",
      "线电压（电流）与相电压（电流）的关系",
      "对称三相电路的计算",
      "不对称三相电路的概念",
      "三相电路的功率",
    ],
    core: true,
    readTime: "15–25",
  },
  {
    slug: "complex-euler",
    title: "复数运算与欧拉公式",
    category: "正弦稳态",
    folder: "ac",
    description:
      "从直角坐标和极坐标出发，掌握加减乘除、共轭、欧拉公式与象限判断。",
    keywords: ["欧拉", "复数", "共轭", "指数", "角度", "弧度"],
    core: true,
  },
  {
    slug: "phasor-diagrams",
    title: "相量图的画法与技巧",
    category: "正弦稳态",
    folder: "ac",
    description:
      "选择共同参考，按首尾相接法画串联电压和并联电流，理解超前与滞后。",
    keywords: ["相量图", "向量图", "画图", "首尾相接", "超前", "滞后"],
    core: true,
  },
];
export const additionalReferences: Record<
  string,
  { section: string; pages: string }
> = {
  "chapter-1-summary": {
    section: "§1-1、§1-2、§1-3、§1-4、§1-5、§1-6、§1-7、§1-8",
    pages: "7起（本章各节首页见正文）",
  },
  "chapter-2-summary": {
    section: "§2-1、§2-2、§2-3、§2-4、§2-5、§2-6、§2-7",
    pages: "32起（本章各节首页见正文）",
  },
  "chapter-3-summary": {
    section: "§3-1、§3-2、§3-3、§3-4、§3-5、§3-6",
    pages: "52起（本章各节首页见正文）",
  },
  "chapter-4-summary": {
    section: "§4-1、§4-2、§4-3、§4-4",
    pages: "82起（本章各节首页见正文）",
  },
  "chapter-6-summary": {
    section: "§6-1、§6-2、§6-3",
    pages: "126起（本章各节首页见正文）",
  },
  "chapter-7-summary": {
    section: "§7-1、§7-2、§7-3、§7-4",
    pages: "137起（本章各节首页见正文）",
  },
  "chapter-8-summary": {
    section: "§8-1、§8-2、§8-3、§8-4",
    pages: "202起（本章各节首页见正文）",
  },
  "chapter-9-summary": {
    section: "§9-1、§9-2、§9-3、§9-4、§9-5、§9-6",
    pages: "220起（本章各节首页见正文）",
  },
  "chapter-10-summary": {
    section: "§10-1、§10-2、§10-3、§10-5",
    pages: "252起（本章各节首页见正文）",
  },
  "chapter-11-summary": {
    section: "§11-2、§11-4",
    pages: "281起（本章各节首页见正文）",
  },
  "chapter-12-summary": {
    section: "§12-1、§12-2、§12-3、§12-4、§12-5",
    pages: "301起（本章各节首页见正文）",
  },
  "complex-euler": {
    section: "§8-1",
    pages: "202–204",
  },
  "phasor-diagrams": {
    section: "§9-2",
    pages: "226–227",
  },
};
