export type FormulaEntry = {
  name: string;
  latex: string;
  position: readonly [chapter: number, section: number, sequence: number];
  supplemental?: boolean;
  slug: string;
  condition: string;
  parameters: string[];
  source: string;
};
const formulaEntries: FormulaEntry[] = [
  {
    name: "电流和电压的参考方向关系",
    latex: "i=\\frac{\\mathrm dq}{\\mathrm dt},\\qquad u_{ab}=v_a-v_b",
    position: [1, 2, 20],
    slug: "chapter-1-summary",
    condition:
      "电流方向和电压极性是人为规定的参考。先规定方向，计算结果为负才表示实际方向相反。电流进入电压正端称关联参考方向，用它统一元件功率和伏安关系。",
    parameters: [
      "q：通过参考截面的电荷，单位C",
      "t：时间，单位s",
      "i：按参考箭头取代数值的电流，单位A",
      "uab：A端对B端的电压，单位V",
      "va、vb：A、B相对同一参考点的电位，单位V",
    ],
    source: "第5版§1-2（本节始于p.9），按同一参考方向整理",
  },
  {
    name: "瞬时功率",
    latex: "p=ui",
    position: [1, 3, 1],
    slug: "kcl-kvl",
    condition: "采用关联参考方向；p>0表示吸收功率，p<0表示发出功率。",
    parameters: [
      "p：元件瞬时功率，关联方向下正值表示吸收，单位W",
      "u：该元件两端的瞬时电压，单位V",
      "i：流入电压正端的瞬时电流，单位A",
    ],
    source: "第5版 p.11，§1-3",
  },
  {
    name: "欧姆定律",
    latex: "u=Ri",
    position: [1, 5, 1],
    slug: "kcl-kvl",
    condition: "线性电阻，电压电流取关联参考方向。",
    parameters: [
      "u：电阻两端的电压，单位V",
      "i：流入电压正端的电流，单位A",
      "R：这只电阻的阻值，单位Ω",
    ],
    source: "第5版 p.13，式（1-3）",
  },
  {
    name: "电阻功率",
    latex: "p=Ri^2=\\frac{u^2}{R}",
    position: [1, 5, 2],
    slug: "kcl-kvl",
    condition: "线性电阻，电压电流取关联参考方向。",
    parameters: [
      "p：电阻吸收的功率，单位W",
      "R：该电阻的阻值，单位Ω",
      "u：该电阻两端电压，单位V",
      "i：流过该电阻的电流，单位A",
    ],
    source: "第5版p.15，式（1-5）",
  },
  {
    name: "电压源和电流源关系",
    latex: "u=U_S\\quad\\text{或}\\quad i=I_S",
    position: [1, 6, 20],
    slug: "chapter-1-summary",
    condition:
      "理想电压源约束端电压，其电流由外电路决定；理想电流源约束电流，其端电压由外电路决定。电压源置零等效短路，电流源置零等效开路。受约束量与未约束量必须分清。",
    parameters: [
      "US：理想电压源给定的电压，单位V；它的电流由外电路决定",
      "IS：理想电流源给定的电流，单位A；它的端电压由外电路决定",
      "u、i：相应电源的端电压与支路电流，分别为V、A",
    ],
    source: "第5版§1-6（本节始于p.16），按同一参考方向整理",
  },
  {
    name: "基尔霍夫电流定律",
    latex: "\\sum i=0",
    position: [1, 8, 1],
    slug: "kcl-kvl",
    condition: "集总电路节点，流入与流出符号相反。",
    parameters: [
      "i：各支路按统一流入/流出约定取符号的电流，单位A",
      "Σ：把相关支路电流逐项作代数求和，不是只加绝对值",
    ],
    source: "第5版 p.21，§1-8",
  },
  {
    name: "基尔霍夫电压定律",
    latex: "\\sum u=0",
    position: [1, 8, 2],
    slug: "kcl-kvl",
    condition: "集总电路的闭合回路，沿统一绕行方向取电压代数值。",
    parameters: [
      "u：沿统一绕行方向取符号的支路电压，单位V",
      "Σ：沿闭合回路逐项作电压代数求和",
    ],
    source: "第5版p.22，§1-8",
  },
  {
    name: "电阻的串联和并联关系",
    latex:
      "\\begin{aligned}R_s&=\\sum R_k,&G_p&=\\sum G_k\\\\u_k&=\\frac{R_k}{R_s}u,&i_k&=\\frac{G_k}{G_p}i\\end{aligned}",
    position: [2, 3, 20],
    slug: "chapter-2-summary",
    condition:
      "串联元件流过同一电流，并联元件跨在同一对结点。串联分压按电阻成正比，并联分流按电导成正比；两支路分流也可用对侧电阻写比例。",
    parameters: [
      "Rk（Rₖ）：第k只电阻的阻值，单位Ω；k是编号，不是乘法",
      "Rs：串联组合的总等效电阻，单位Ω",
      "Gk=1/Rk：第k支路电导，单位S",
      "Gp：并联组合的总电导，单位S",
      "uk：第k只串联电阻的分压，单位V；u为组合总电压",
      "ik：第k条并联支路的分流，单位A；i为组合总电流",
      "Σ：对组合内所有k项求和",
    ],
    source: "第5版§2-3（本节始于p.33），按同一参考方向整理",
  },
  {
    name: "三角形转星形",
    latex: "R_1=\\frac{R_{12}R_{31}}{R_{12}+R_{23}+R_{31}}",
    position: [2, 4, 1],
    slug: "star-delta",
    condition: "端子1相邻的两条Δ电阻相乘，再除以三边之和。",
    parameters: [
      "R12、R23、R31：Δ中连接对应两个外端子的边电阻，单位Ω",
      "R1：Y中端子1连接到中心点的电阻，单位Ω；其他Y支路同理",
      "下标12表示连接端子1和2，不是R乘12",
    ],
    source: "第5版式（2-8）",
  },
  {
    name: "对称星三角变换",
    latex: "R_\\Delta=3R_Y",
    position: [2, 4, 2],
    slug: "star-delta",
    condition: "三个电阻相等；保持三个外部端子等效。",
    parameters: [
      "RΔ：对称Δ连接中每一边的电阻，单位Ω",
      "RY：端口等效Y连接中每一支路的电阻，单位Ω",
      "此式比较的是每边/每支值，不是三只电阻的总和",
    ],
    source: "第5版 p.39，§2-4",
  },
  {
    name: "电压源并联电流源",
    latex: "u=U_S",
    position: [2, 5, 2],
    slug: "source-transformations",
    condition:
      "完整理想二端组合的对外等效；保持端口和参考方向，内部电压、电流、功率须在原网络中另算。",
    parameters: [
      "u：该组合的端电压，单位V",
      "US：理想电压源规定的电压，单位V",
      "IS：内部电流源规定的电流，单位A；不改变理想电压源固定的端电压",
    ],
    source: "由教材理想源定义与§2-5、§2-6的端口关系推得",
  },
  {
    name: "电压源串联电流源",
    latex: "i=I_S",
    position: [2, 5, 3],
    slug: "source-transformations",
    condition:
      "完整理想二端组合的对外等效；保持端口和参考方向，内部电压、电流、功率须在原网络中另算。",
    parameters: [
      "i：从A端流向外部负载的输出电流，单位A；IS箭头指向A",
      "IS：理想电流源规定的电流，单位A；串联中点不能另接支路",
      "US：串联电压源规定的电压，单位V；不改变该串联电流",
    ],
    source: "由教材理想源定义与§2-5、§2-6的端口关系推得",
  },
  {
    name: "电压源并联电阻",
    latex: "u=U_S",
    position: [2, 5, 4],
    slug: "source-transformations",
    condition:
      "完整理想二端组合的对外等效；保持端口和参考方向，内部电压、电流、功率须在原网络中另算。",
    parameters: [
      "u：该组合的端电压，单位V",
      "US：理想电压源规定的电压，单位V",
      "R：原组合内部的电阻，单位Ω；原有压降或损耗仍应在原网络中计算",
    ],
    source: "由教材理想源定义与§2-5、§2-6的端口关系推得",
  },
  {
    name: "电流源串联电阻",
    latex: "i=I_S",
    position: [2, 5, 5],
    slug: "source-transformations",
    condition:
      "完整理想二端组合的对外等效；保持端口和参考方向，内部电压、电流、功率须在原网络中另算。",
    parameters: [
      "i：从A端流向外部负载的输出电流，单位A；IS箭头指向A",
      "IS：理想电流源规定的电流，单位A；串联中点不能另接支路",
      "R：原组合内部的电阻，单位Ω；原有压降或损耗仍应在原网络中计算",
    ],
    source: "由教材理想源定义与§2-5、§2-6的端口关系推得",
  },
  {
    name: "电压源、电流源的串联和并联关系",
    latex: "U_{eq}=\\sum U_{Sk},\\qquad I_{eq}=\\sum I_{Sk}",
    position: [2, 5, 20],
    slug: "chapter-2-summary",
    condition:
      "串联电压源的电压按极性相加，并联电流源的电流按方向相加。理想电压源并联必须电压一致，理想电流源串联必须电流一致，否则约束矛盾。源的未约束量由外部电路决定。",
    parameters: [
      "Ueq：串联电压源组合的等效电压，单位V",
      "USk：第k个电压源按统一极性取符号的电压，单位V",
      "Ieq：并联电流源组合的等效电流，单位A",
      "ISk：第k个电流源按统一方向取符号的电流，单位A",
      "eq表示equivalent（等效），k是编号，Σ是代数求和",
    ],
    source: "第5版§2-5（本节始于p.41），按同一参考方向整理",
  },
  {
    name: "电源等效变换",
    latex: "I_S=\\frac{U_S}{R},\\quad U_S=RI_S",
    position: [2, 6, 1],
    slug: "source-transformations",
    condition: "电压源串联R与电流源并联R的完整二端组合；方向由负端指向正端。",
    parameters: [
      "US：串联电阻模型中的理想电压源电压，单位V",
      "IS：等效并联电阻模型中的理想电流源电流，单位A",
      "R：变换前后保留的同一电阻，单位Ω",
    ],
    source: "第5版式（2-11）的电阻形式",
  },
  {
    name: "输入电阻定义",
    latex: "R_{in}=\\frac ui",
    position: [2, 7, 0],
    slug: "input-resistance",
    condition: "无独立源的线性一端口；u、i为所选输入端口的关联量。",
    parameters: [
      "Rin：从所选端口看入的输入电阻，单位Ω",
      "u：端口电压，单位V",
      "i：由外部流入端口正端的电流，单位A；含独立源时不能直接用工作点u/i求Req",
    ],
    source: "第5版§2-7，式（2-12）",
  },
  {
    name: "输入电阻测试源法",
    latex: "R_{in}=\\frac{u_t}{i_t}",
    position: [2, 7, 1],
    slug: "input-resistance",
    condition: "独立源置零、受控源保留；it取流入网络正端。",
    parameters: [
      "Rin：从所选端口看入的输入电阻，单位Ω",
      "Req：独立源置零后，该端口看到的网络等效电阻，单位Ω；不含外部负载RL",
      "ut：加在端口的测试电压，单位V",
      "it：由测试源流入端口正端的电流，单位A；不是向负载输出的电流",
    ],
    source: "第5版式（2-12）",
  },
  {
    name: "桥臂一端口开路电压",
    latex: "u_{oc}=U_S+I_SR",
    supplemental: true,
    position: [2, 7, 2],
    slug: "bridge-arm",
    condition: "仅对应本站图中US左正右负、IS从X指向A的拓扑和方向。",
    parameters: [
      "uoc：A对B的开路端电压，单位V；oc表示open circuit",
      "US：下方独立电压源电压，单位V，按图左正右负",
      "IS：上方电流源电流，单位A，按图X→A",
      "R：与上方电流源并联的电阻，单位Ω",
    ],
    source: "原创拓扑，由KCL/KVL推得",
  },
  {
    name: "电路的图关系",
    latex: "b_t=n-1,\\qquad b_l=b-n+1",
    position: [3, 1, 20],
    slug: "chapter-3-summary",
    condition:
      "图保留结点和支路的连接关系，忽略元件形状与参数。树是包含全部结点而不形成回路的连通子图，非树支路是连支。支路划分可按元件或串联组合，但结点与支路数要同步。",
    parameters: [
      "n：按当前划分得到的结点总数，无量纲",
      "b：按同一划分得到的支路总数，无量纲",
      "bt：树支数，连通图中等于n−1",
      "bl：连支数，也等于一组基本回路的数量b−n+1",
    ],
    source: "第5版§3-1（本节始于p.52），按同一参考方向整理",
  },
  {
    name: "KCL和KVL的独立方程数关系",
    latex: "N_{KCL}=n-1,\\quad N_{KVL}=b-n+1",
    position: [3, 2, 20],
    slug: "chapter-3-summary",
    condition:
      "连通网络的独立KCL方程数为n−1，独立KVL方程数为b−n+1，两者合计b。其余结点或回路方程能由它们线性组合得到。方程独立性与元件参数无关。",
    parameters: [
      "n：结点数，b：支路数，须使用同一建图划分",
      "NKCL：独立结点电流方程数量",
      "NKVL：独立回路电压方程数量；不是所有简单回路的总数",
    ],
    source: "第5版§3-2（本节始于p.54），按同一参考方向整理",
  },
  {
    name: "支路电流法关系",
    latex: "i_1-i_2-i_3=0,\\quad R_1i_1+R_2i_2=U_S,\\quad R_2i_2=R_3i_3",
    position: [3, 3, 20],
    slug: "chapter-3-summary",
    condition:
      "以各支路电流为未知量，写n−1个KCL，再用元件关系把b−n+1个KVL写成电流方程。方法通用但未知量往往较多，适合结构简单、支路电流本身是目标的题目。",
    parameters: [
      "i1、i2、i3：按题图参考方向定义的三条支路电流，单位A",
      "R1、R2、R3：相应支路电阻，单位Ω",
      "US：该示例电路的电源电压，单位V",
      "这些方程针对所示三支路结构，不能直接套入任意拓扑",
    ],
    source: "第5版§3-3（本节始于p.58），按同一参考方向整理",
  },
  {
    name: "双网孔方程",
    latex:
      "\\begin{aligned}(R_1+R_2)i_{m1}-R_2i_{m2}&=u_{S1}-u_{S2}\\\\-R_2i_{m1}+(R_2+R_3)i_{m2}&=u_{S2}-u_{S3}\\end{aligned}",
    position: [3, 4, 1],
    slug: "mesh-analysis",
    condition:
      "对应教材图3-9，两网孔均按教材方向；公共支路电流为网孔电流之差。",
    parameters: [
      "im1、im2：两个参考网孔电流，单位A；m表示mesh（网孔）",
      "R1、R2、R3：对应支路电阻，单位Ω；R2为公共电阻",
      "uS1、uS2、uS3：对应支路的电源电压，单位V；电源项按绕行方向取符号",
    ],
    source: "第5版p.61–62，式（3-6）",
  },
  {
    name: "回路电流法关系",
    latex:
      "i_k=\\sum_{m=1}^{b-n+1}\\sigma_{km}i_{lm},\\qquad \\sigma_{km}\\in\\{-1,0,1\\}",
    position: [3, 5, 20],
    slug: "chapter-3-summary",
    condition:
      "回路法适用于一般连通网络。选一棵树，每加入一条连支形成一个基本回路，令其回路电流与该连支方向一致；树支电流是多个回路电流的代数和。网孔法是平面网络的一种便利选择。",
    parameters: [
      "ik：第k条支路的实际参考电流，单位A",
      "ilm：第m个基本回路的参考环流，单位A",
      "σkm：第m回路经过第k支路的方向系数，同向+1、反向−1、不经过0",
      "b−n+1：连通图中独立回路数量；k、m均为编号",
    ],
    source: "第5版§3-5（本节始于p.64），按同一参考方向整理",
  },
  {
    name: "结点电压方程（第一行）",
    latex: "G_{11}u_{n1}+G_{12}u_{n2}+G_{13}u_{n3}=i_{S11}",
    position: [3, 6, 1],
    slug: "nodal-analysis",
    condition: "教材三独立结点方程的第一行；自导为正，互导为负。",
    parameters: [
      "un1、un2、un3：各结点相对参考结点的电压，单位V；n标记node（结点）",
      "G11：结点1所连电导之和，单位S",
      "G12、G13：对应两结点间电导的负值，单位S",
      "iS11：流入结点1的电流源代数和，单位A",
    ],
    source: "第5版p.70，式（3-18）的第一行",
  },
  {
    name: "叠加的功率交叉项",
    latex: "p=R(i'+i'')^2",
    position: [4, 1, 1],
    slug: "superposition",
    condition: "先叠加同一电阻中的分电流再求功率，不能仅加两个分功率。",
    parameters: [
      "i′、i″：同一电阻中各独立源分别作用时的带符号电流，单位A",
      "R：该电阻的阻值，单位Ω",
      "p：总电流作用下的电阻功率，单位W；不能直接相加分功率",
    ],
    source: "由第5版p.85的功率限制展开",
  },
  {
    name: "替代定理关系",
    latex: "u_S=u_p\\quad\\text{或}\\quad i_S=i_p",
    position: [4, 2, 20],
    slug: "chapter-4-summary",
    condition:
      "已知某二端子部分的端电压和电流，可用相同电压的理想电压源或相同电流的理想电流源替代，在原工作状态下保持其余网络的电压电流。要保证替代后解存在且唯一。它不等于对任意负载都成立的端口等效。",
    parameters: [
      "up、ip：原二端部分在当前工作点的端电压、端电流，分别为V、A",
      "uS或iS：用于替代的理想源值，分别为V、A",
      "p在此是端口标记，不是功率；替代须保持参考方向与解的唯一性",
    ],
    source: "第5版§4-2（本节始于p.88），按同一参考方向整理",
  },
  {
    name: "开路短路求等效电阻",
    latex: "R_{eq}=\\frac{u_{oc}}{i_{sc}}",
    position: [4, 3, 1],
    slug: "thevenin",
    condition: "线性一端口；isc有限且非零，按对应端口方向取代数值。",
    parameters: [
      "Req：指定源侧端口的等效电阻，单位Ω；负载移去、独立源置零后从端口看入",
      "uoc：原网络该端口的开路电压，单位V；oc表示开路",
      "isc：原网络端口外部短路线中的电流，单位A；sc表示短路",
      "isc须有限且非零；uoc=isc=0时改用测试源法",
    ],
    source: "第5版式（4-5）",
  },
  {
    name: "最大功率传输定理关系",
    latex: "R_L=R_{eq},\\qquad P_{max}=\\frac{u_{oc}^2}{4R_{eq}}",
    position: [4, 4, 20],
    slug: "chapter-4-summary",
    condition:
      "对固定的线性直流戴维宁源，若Req>0且可调负载是正电阻，RL=Req时负载获得最大功率。这里优化的是负载功率，不是效率；负载变化时要保持源侧等效参数不变。",
    parameters: [
      "RL：可调的外部负载电阻，单位Ω",
      "Req：从负载端口看入源侧的等效电阻，单位Ω；不含RL",
      "uoc：源侧开路电压，单位V",
      "Pmax：满足匹配条件时负载得到的最大功率，单位W",
    ],
    source: "第5版§4-4（本节始于p.97），按同一参考方向整理",
  },
  {
    name: "电容伏安关系",
    latex: "i=C\\frac{du}{dt}",
    position: [6, 1, 1],
    slug: "capacitor",
    condition: "理想线性电容，关联参考方向。",
    parameters: [
      "C：理想线性电容的电容量，单位F",
      "u：电容两端瞬时电压，单位V",
      "i：流入电压正端的瞬时电流，单位A",
      "du/dt：电容电压的变化率，单位V/s",
    ],
    source: "第5版 p.126，式（6-2）",
  },
  {
    name: "电容储能",
    latex: "W_C(t)=\\frac12 Cu^2(t)",
    position: [6, 1, 2],
    slug: "capacitor",
    condition: "理想线性电容。",
    parameters: [
      "WC(t)：时刻t电容中储存的电场能量，单位J",
      "C：电容量，单位F",
      "u(t)：同一时刻的电容电压，单位V；平方后不保留电压正负号",
    ],
    source: "第5版 p.128，式（6-8）",
  },
  {
    name: "电感伏安关系",
    latex: "u=L\\frac{di}{dt}",
    position: [6, 2, 1],
    slug: "inductor",
    condition: "理想线性电感，关联参考方向。",
    parameters: [
      "L：理想线性电感的电感量，单位H",
      "i：电感中的瞬时电流，单位A",
      "u：与电流关联参考方向的端电压，单位V",
      "di/dt：电感电流的变化率，单位A/s",
    ],
    source: "第5版 p.130，式（6-11）",
  },
  {
    name: "电感储能",
    latex: "W_L(t)=\\frac12 Li^2(t)",
    position: [6, 2, 2],
    slug: "inductor",
    condition: "理想线性电感。",
    parameters: [
      "WL(t)：时刻t电感中储存的磁场能量，单位J",
      "L：电感量，单位H",
      "i(t)：同一时刻的电感电流，单位A",
    ],
    source: "第5版 p.130，式（6-16）的电流形式",
  },
  {
    name: "电容、电感元件的串联与并联关系",
    latex:
      "C_p=\\sum C_k,\\quad\\frac1{C_s}=\\sum\\frac1{C_k},\\quad L_s=\\sum L_k,\\quad\\frac1{L_p}=\\sum\\frac1{L_k}",
    position: [6, 3, 20],
    slug: "chapter-6-summary",
    condition:
      "并联电容电压相同，电容值相加；串联电容按倒数相加。无互感的串联电感电流相同，电感值相加；并联电感按倒数相加。初始储能与电荷约束仍要另外保留。",
    parameters: [
      "Ck、Lk：第k个电容或电感的参数，分别为F、H",
      "Cp、Cs：电容并联、串联组合的等效电容量，单位F",
      "Ls、Lp：电感串联、并联组合的等效电感量，单位H",
      "p、s分别表示parallel（并联）、series（串联）；k是编号，Σ表示逐项求和",
      "电感合并式要求无互感，带初始储能时还要保留初始条件",
    ],
    source: "第5版§6-3（本节始于p.131），按同一参考方向整理",
  },
  {
    name: "动态电路的方程及其初始条件关系",
    latex:
      "u_C(0_+)=u_C(0_-),\\quad i_L(0_+)=i_L(0_-),\\quad RC\\frac{\\mathrm du_C}{\\mathrm dt}+u_C=U_S",
    position: [7, 1, 20],
    slug: "chapter-7-summary",
    condition:
      "本学习范围只考虑一阶电路。换路前直流稳态用电容开路、电感短路求初值；换路后先用电容电压、电感电流连续性，再通过KCL/KVL求其余瞬时量。切换后的等效网络决定响应，不沿用旧网络的时间常数。",
    parameters: [
      "uC：电容电压，单位V；iL：电感电流，单位A",
      "0−：换路前一瞬间，0+：换路后一瞬间",
      "R：所示串联RC的电阻，单位Ω；C：电容量，单位F",
      "US：接入的恒定直流电源电压，单位V",
      "duC/dt：电容电压变化率，单位V/s；连续性关系用于通常换路条件",
    ],
    source: "第5版§7-1（本节始于p.137），按同一参考方向整理",
  },
  {
    name: "RC 时间常数",
    latex: "\\tau=RC",
    position: [7, 2, 1],
    slug: "rc-circuit",
    condition: "R 为电容端口看到的等效电阻，R>0。",
    parameters: [
      "τ：指数响应变化快慢的时间尺度，单位s，不是完全充满的时间",
      "R：从电容端口看入、独立源置零后的等效电阻，也记Req，单位Ω",
      "C：被分析电容的电容量，单位F",
    ],
    source: "第5版 p.141，§7-2",
  },
  {
    name: "RL 时间常数",
    latex: "\\tau=\\frac{L}{R_{eq}}",
    position: [7, 2, 2],
    slug: "rl-circuit",
    condition: "R为电感端口看到的等效电阻，Req>0；独立源置零、受控关系保留。",
    parameters: [
      "τ：指数响应的时间常数，单位s",
      "L：被分析电感的电感量，单位H",
      "Req：从电感端口看入、独立源置零后的等效电阻，单位Ω；受控关系保留",
    ],
    source: "第5版p.144，§7-2",
  },
  {
    name: "RL 零输入响应",
    latex: "i_L(t)=I_0e^{-t/\\tau}",
    position: [7, 2, 3],
    slug: "rl-circuit",
    condition: "无外部独立激励，由初始电感储能产生的一阶响应，τ=L/Req。",
    parameters: [
      "iL(t)：时刻t的电感电流，单位A",
      "I0：换路后初始电感电流iL(0+)，单位A",
      "τ=L/Req：该电感端口的时间常数，单位s",
      "t：换路后的时间，单位s；t/τ必须无量纲",
    ],
    source: "第5版§7-2，p.144",
  },
  {
    name: "一阶电路的零状态响应关系",
    latex:
      "u_C(t)=U_S(1-e^{-t/\\tau}),\\qquad i_L(t)=\\frac{U_S}{R}(1-e^{-t/\\tau})",
    position: [7, 3, 20],
    slug: "chapter-7-summary",
    condition:
      "零状态表示初始电容电压或电感电流为0，响应仅由外部激励引起。本页只讨论t=0接入恒定直流源后的普通充电、建流，不展开阶跃或冲激专题。初始值为0不等于响应一直为0。",
    parameters: [
      "uC(t)、iL(t)：零初始状态下的电容电压或电感电流，分别为V、A",
      "US：接入的恒定直流电压，单位V",
      "R：相应串联电路的等效电阻，单位Ω",
      "τ：RC用RC，RL用L/R，单位s；t为换路后时间，单位s",
    ],
    source: "第5版§7-3（本节始于p.147），按同一参考方向整理",
  },
  {
    name: "一阶电路的全响应关系",
    latex: "f(t)=f(\\infty)+[f(0_+)-f(\\infty)]e^{-t/\\tau}",
    position: [7, 4, 20],
    slug: "chapter-7-summary",
    condition:
      "全响应同时包含初始储能与外部激励。三要素是0+初值、∞终值和时间常数；也可写为零输入加零状态，或稳态分量加暂态分量。两种分解角度不同，零输入不等于暂态的同义词。",
    parameters: [
      "f(t)：待求响应，可取uC(t)或iL(t)，单位分别为V或A",
      "f(0+)：换路刚完成时的初始值，与f(t)同单位",
      "f(∞)：长时间后的终值，与f(t)同单位",
      "τ：换路后网络的时间常数，单位s；t：换路后时间，单位s",
      "∞表示长时间极限，不是把无穷大直接当作普通数代入",
    ],
    source: "第5版§7-4（本节始于p.152），按同一参考方向整理",
  },
  {
    name: "欧拉公式",
    latex: "e^{j\\theta}=\\cos\\theta+j\\sin\\theta",
    position: [8, 1, 1],
    slug: "complex-euler",
    condition: "指数中的角使用弧度，j²=−1。",
    parameters: [
      "j：虚数单位，j²=−1，无量纲",
      "θ：指数中的角，使用弧度rad",
      "e：自然对数的底；ejθ在复平面表示单位模、辐角θ的复数",
    ],
    source: "第5版§8-1，p.202–204的同一数学关系",
  },
  {
    name: "余弦的指数形式",
    latex: "\\cos\\theta=\\frac{e^{j\\theta}+e^{-j\\theta}}2",
    position: [8, 1, 2],
    slug: "complex-euler",
    condition: "指数中的角使用弧度，j²=−1。",
    parameters: [
      "θ：角，指数运算中使用rad",
      "j：虚数单位，j²=−1",
      "e的正负指数对应旋转方向相反的一对单位复数",
    ],
    source: "第5版§8-1，p.202–204的同一数学关系",
  },
  {
    name: "正弦的指数形式",
    latex: "\\sin\\theta=\\frac{e^{j\\theta}-e^{-j\\theta}}{2j}",
    position: [8, 1, 3],
    slug: "complex-euler",
    condition: "指数中的角使用弧度，j²=−1。",
    parameters: [
      "θ：角，指数运算中使用rad",
      "j：虚数单位；分母2j不可误写成2",
      "这里的sinθ为无量纲三角函数值",
    ],
    source: "第5版§8-1，p.202–204的同一数学关系",
  },
  {
    name: "正弦量关系",
    latex:
      "u=U_m\\cos(\\omega t+\\phi),\\quad U=\\frac{U_m}{\\sqrt2},\\quad\\omega=2\\pi f,\\quad T=\\frac1f",
    position: [8, 2, 20],
    slug: "chapter-8-summary",
    condition:
      "正弦量由峰值、角频率和初相位决定。有效值用于同频正弦功率和有效值相量。先把sin改为共同的cos参考，再提取初相位；相位超前通常对应波形向左移动。不同频率的两量不能用一个固定相位差描述。",
    parameters: [
      "Um：电压峰值，U：电压有效值，单位V",
      "ω：角频率，单位rad/s；f：频率，单位Hz",
      "T：周期，单位s；φ：初相位，必须与ωt统一角度单位",
      "t：时间，单位s；u：瞬时电压，单位V",
    ],
    source: "第5版§8-2（本节始于p.205），按同一参考方向整理",
  },
  {
    name: "相量对应的瞬时量",
    latex: "u=\\sqrt2 U\\cos(\\omega t+\\phi_u)",
    position: [8, 3, 1],
    slug: "phasor",
    condition: "余弦参考，U使用有效值；瞬时量与相量是对应关系。",
    parameters: [
      "u(t)：随时间变化的瞬时电压，单位V",
      "U：电压有效值，单位V；√2U才是正弦峰值",
      "ω：共同角频率，单位rad/s；t：时间，单位s",
      "φu：电压初相位；与ωt相加时统一为弧度",
    ],
    source: "第5版p.209，§8-3",
  },
  {
    name: "有效值相量",
    latex: "\\dot U=Ue^{j\\phi_u}=U\\angle\\phi_u",
    position: [8, 3, 2],
    slug: "phasor",
    condition: "同频正弦稳态、余弦参考；U使用有效值。",
    parameters: [
      "U̇：记录有效值和初相位的电压相量，单位V",
      "U：电压有效值，单位V；φu：初相位",
      "上方点号表示相量，不是时间导数；∠表示极坐标相角",
      "j为虚数单位，指数中的φu使用弧度",
    ],
    source: "第5版p.210，§8-3",
  },
  {
    name: "电路定律的相量形式关系",
    latex:
      "\\sum\\dot I=0,\\quad\\sum\\dot U=0,\\quad\\dot U_R=R\\dot I,\\quad\\dot U_L=j\\omega L\\dot I,\\quad\\dot U_C=\\frac{\\dot I}{j\\omega C}",
    position: [8, 4, 20],
    slug: "chapter-8-summary",
    condition:
      "在同频线性正弦稳态中，KCL、KVL仍成立，但变量换成相量；R、L、C的伏安关系分别对应R、jωL、1/(jωC)。电感电压超前电流90°，电容电压滞后电流90°。",
    parameters: [
      "U̇、İ：同频有效值电压、电流相量，分别为V、A",
      "下标R、L、C：对应电阻、电感、电容元件",
      "R、L、C：元件参数，分别为Ω、H、F；ω：角频率，单位rad/s",
      "Σ：对结点电流或闭合回路电压取代数和",
    ],
    source: "第5版§8-4（本节始于p.211），按同一参考方向整理",
  },
  {
    name: "电阻阻抗",
    latex: "Z_R=R",
    position: [9, 1, 1],
    slug: "impedance",
    condition: "理想电阻，同频正弦稳态。",
    parameters: [
      "ZR：电阻元件的阻抗，单位Ω",
      "R：该电阻的阻值，单位Ω；纯电阻的阻抗相角为0",
    ],
    source: "第5版 p.223，§9-1",
  },
  {
    name: "电感阻抗",
    latex: "Z_L=j\\omega L",
    position: [9, 1, 2],
    slug: "impedance",
    condition: "理想电感，同频正弦稳态。",
    parameters: [
      "ZL：理想电感的阻抗，单位Ω",
      "L：电感量，单位H；ω：角频率，单位rad/s",
      "j：虚数单位，表示电压相对电流超前90°",
    ],
    source: "第5版 p.223，§9-1",
  },
  {
    name: "电容阻抗",
    latex: "Z_C=-j\\frac1{\\omega C}",
    position: [9, 1, 3],
    slug: "impedance",
    condition: "理想电容，ω>0，同频正弦稳态。",
    parameters: [
      "ZC：理想电容的阻抗，单位Ω",
      "C：电容量，单位F；ω：角频率，单位rad/s且须大于0",
      "−j：负虚部方向，表示电容电压滞后电流90°",
    ],
    source: "第5版 p.223，§9-1",
  },
  {
    name: "电路的相量图关系",
    latex: "\\dot U=\\dot U_R+\\dot U_L+\\dot U_C",
    position: [9, 2, 20],
    slug: "chapter-9-summary",
    condition:
      "相量图是复数方程的几何表示。串联取共同电流作参考，并联取共同电压作参考。等量纲相量按同一比例尺首尾相接，最终起点到终点的箭头为总量。相量可平移，不能随意改变长度或方向。",
    parameters: [
      "U̇：串联回路总电压相量，单位V",
      "U̇R、U̇L、U̇C：各元件电压相量，单位V",
      "İ：串联回路的共同电流相量，单位A",
      "XL=ωL、XC=1/(ωC)：感抗、容抗的非负大小，单位Ω",
      "j(XL−XC)：净电抗的虚部，符号决定感性或容性",
    ],
    source: "第5版§9-2（本节始于p.226），按同一参考方向整理",
  },
  {
    name: "有功功率",
    latex: "P=UI\\cos\\phi_Z",
    position: [9, 4, 1],
    slug: "power",
    condition: "U、I 使用有效值，同频正弦稳态。",
    parameters: [
      "P：平均有功功率，单位W",
      "U、I：同一端口的正弦有效值，分别为V、A",
      "φZ：电压相位减电流相位，即阻抗角；不一定等于任意两个相量的夹角",
    ],
    source: "第5版 p.235，§9-4",
  },
  {
    name: "功率因数",
    latex: "\\lambda=\\cos\\phi_Z=\\frac{P}{S}",
    position: [9, 4, 2],
    slug: "power-factor",
    condition: "同频正弦条件；含谐波时不能仅用相位差余弦。",
    parameters: [
      "λ：有功功率占视在功率的比例，无量纲",
      "P：有功功率，单位W；S：视在功率，单位VA",
      "φZ：电压相位减电流相位；λ=cosφZ用于正弦条件",
    ],
    source: "第5版p.236，§9-4",
  },
  {
    name: "并联电容补偿",
    latex: "C=\\frac{P(\\tan\\phi_1-\\tan\\phi_2)}{\\omega U^2}",
    position: [9, 4, 3],
    slug: "power-factor",
    condition: "理想正弦单相并联补偿，电压保持不变。",
    parameters: [
      "C：与负载并联的补偿电容，单位F",
      "P：负载有功功率，单位W；U：负载端有效电压，单位V",
      "ω=2πf：角频率，单位rad/s",
      "φ1、φ2：补偿前、后电源侧电压与电流的相位差；两者三角函数要用同一角度制",
    ],
    source: "第5版p.241，等价写法",
  },
  {
    name: "复功率关系",
    latex: "\\overline S=\\dot U\\dot I^*=P+jQ,\\qquad S=\\sqrt{P^2+Q^2}",
    position: [9, 5, 20],
    slug: "chapter-9-summary",
    condition:
      "关联方向下复功率为电压相量乘电流相量共轭，实部为P、虚部为Q，其模为S。复功率可按支路相加，但不同支路视在功率的大小不能一般直接相加。复功率不是电压电流的同频相量。",
    parameters: [
      "S̄：复功率，等于P+jQ，通常以VA表示",
      "P：有功功率，单位W；Q：无功功率，单位var",
      "S：复功率的模，即视在功率，单位VA",
      "U̇、İ：同端口的有效值相量，分别为V、A；星号*表示复共轭，不是乘法",
    ],
    source: "第5版§9-5（本节始于p.238），按同一参考方向整理",
  },
  {
    name: "最大功率传输关系",
    latex:
      "Z_L=Z_{eq}^*,\\quad P_{max}=\\frac{U_{oc}^2}{4R_{eq}};\\qquad X_L=0:\\ R_L=|Z_{eq}|",
    position: [9, 6, 20],
    slug: "chapter-9-summary",
    condition:
      "固定频率下把源侧化为Uoc与Zeq=Req+jXeq。若负载R、X均可调且Req>0，最佳负载是共轭匹配；若只能调纯电阻，最佳RL是源阻抗的模。约束不同，结论不同。",
    parameters: [
      "Zeq=Req+jXeq：源侧端口等效阻抗，单位Ω；Req是实部，Xeq是电抗",
      "ZL、RL、XL：负载阻抗、电阻与电抗，单位Ω",
      "Uoc：开路电压的有效值，单位V；Pmax：最大负载有功功率，单位W",
      "星号*表示复共轭：实部不变、虚部变号；仅纯电阻可调时条件不同",
    ],
    source: "第5版§9-6（本节始于p.241），按同一参考方向整理",
  },
  {
    name: "耦合因数",
    latex: "k=\\frac{M}{\\sqrt{L_1L_2}}\\leq1",
    position: [10, 1, 1],
    slug: "coupled-inductors",
    condition: "线性、无源的两耦合线圈，M取非负互感大小，0≤k≤1。",
    parameters: [
      "L1、L2：两线圈自感，单位H；M：互感大小，单位H",
      "k：耦合因数，无量纲，线性无源模型中0≤k≤1",
      "此处k是耦合因数，不是求和公式里的编号k",
    ],
    source: "第5版p.255，§10-1",
  },
  {
    name: "含有耦合电感电路的计算关系",
    latex:
      "L_{eq}=L_1+L_2\\pm2M,\\quad\\dot U_1=j\\omega L_1\\dot I_1\\pm j\\omega M\\dot I_2",
    position: [10, 2, 20],
    slug: "chapter-10-summary",
    condition:
      "互感项将两支路方程耦合，不能把每个线圈独立当作jωL处理。串联同向时等效电感L1+L2+2M，反向时L1+L2−2M；更一般的网络要按同名端写联立相量方程。",
    parameters: [
      "Leq：两线圈串联后的等效电感，单位H",
      "L1、L2：各线圈自感，M：互感，单位H",
      "±：按同名端和参考方向选符号；同向串联取+，反向取−",
      "U̇1、İ1、İ2：端口电压与线圈电流相量，分别为V、A；ω单位rad/s",
    ],
    source: "第5版§10-2（本节始于p.257），按同一参考方向整理",
  },
  {
    name: "耦合电感的功率关系",
    latex: "W=\\frac12L_1i_1^2+\\frac12L_2i_2^2\\pm Mi_1i_2",
    position: [10, 3, 20],
    slug: "chapter-10-summary",
    condition:
      "无损耦合电感通过磁场交换能量，总瞬时端口功率等于磁场储能变化率。互感储能项带符号，但无源模型的总能量不能任意为负；正弦稳态下可以在两个端口间传递有功。",
    parameters: [
      "W：两耦合线圈的总磁场储能，单位J",
      "L1、L2、M：自感与互感，单位H",
      "i1、i2：当前时刻的线圈电流，单位A",
      "互感项±与同名端、电流方向的约定一致；式中i是瞬时电流",
    ],
    source: "第5版§10-3（本节始于p.262），按同一参考方向整理",
  },
  {
    name: "变压器原理关系",
    latex:
      "(R_1+j\\omega L_1)\\dot I_1+j\\omega M\\dot I_2=\\dot U_1,\\quad j\\omega M\\dot I_1+(R_2+j\\omega L_2+Z_L)\\dot I_2=0",
    position: [10, 4, 20],
    slug: "chapter-10-summary",
    condition:
      "实际变压器用耦合线圈描述，绕组电阻带来铜耗，漏磁使k小于1，磁化支路需要电流。一次、二次回路通过互阻抗jωM联系。负载会反映到一次侧，开路、短路状态要区分。",
    parameters: [
      "U̇1：一次侧施加的有效值电压相量，单位V",
      "İ1、İ2：按两侧均流入同名端约定的电流相量，单位A",
      "R1、R2：绕组电阻，单位Ω；L1、L2、M：自感与互感，单位H",
      "ZL：二次侧外部负载阻抗，单位Ω；ω单位rad/s",
    ],
    source: "第5版§10-4（本节始于p.265），按同一参考方向整理",
  },
  {
    name: "理想变压器关系",
    latex:
      "\\frac{\\dot U_1}{\\dot U_2}=n,\\quad\\dot I_1=-\\frac{\\dot I_2}{n},\\quad Z_{in}=n^2Z_L",
    position: [10, 5, 20],
    slug: "chapter-10-summary",
    condition:
      "理想模型忽略损耗、漏磁与有限磁化电流，用匝比n=N1/N2规定电压和电流约束。两侧电流均流入同名端时电流比带负号；负载电流采用输出方向时符号相应改变。",
    parameters: [
      "n=N1/N2：一次与二次匝数比，无量纲；n不是结点数",
      "U̇1、U̇2：同名端极性下的两侧电压相量，单位V",
      "İ1、İ2：均流入同名端的电流相量，单位A，因此电流比带负号",
      "ZL：二次负载阻抗，Zin：从一次侧看入的阻抗，单位Ω；折算系数是n²",
    ],
    source: "第5版§10-5（本节始于p.268），按同一参考方向整理",
  },
  {
    name: "RLC串联阻抗",
    latex: "Z(j\\omega)=R+j\\left(\\omega L-\\frac1{\\omega C}\\right)",
    position: [11, 2, 1],
    slug: "rlc",
    condition: "理想R、L、C串联，R>0，ω>0。",
    parameters: [
      "Z(jω)：频率ω处的串联输入阻抗，单位Ω",
      "R、L、C：串联元件参数，分别为Ω、H、F",
      "ωL与1/(ωC)：感抗与容抗大小，单位Ω；ω单位rad/s",
    ],
    source: "第5版p.281，§11-2",
  },
  {
    name: "RLC串联谐振频率",
    latex: "\\omega_0=\\frac1{\\sqrt{LC}},\\qquad f_0=\\frac1{2\\pi\\sqrt{LC}}",
    position: [11, 2, 2],
    slug: "rlc",
    condition: "理想串联RLC，谐振时感抗与容抗相等。",
    parameters: [
      "ω0：谐振角频率，单位rad/s；f0：谐振频率，单位Hz",
      "L：电感量，单位H；C：电容量，单位F",
      "下标0标记谐振点，不表示参数值为0",
    ],
    source: "第5版p.282，§11-2",
  },
  {
    name: "RLC并联谐振电路关系",
    latex:
      "Y=G+j\\left(\\omega C-\\frac1{\\omega L}\\right),\\quad\\omega_0=\\frac1{\\sqrt{LC}},\\quad Z(\\omega_0)=\\frac1G",
    position: [11, 4, 20],
    slug: "chapter-11-summary",
    condition:
      "本节采用教材G、L、C并联模型。谐振条件是总导纳虚部为0，感性支路与容性支路电流相互抵消。固定端电压下电源电流最小，输入阻抗最大为1/G，支路电流仍可很大。",
    parameters: [
      "Y：并联组合总导纳，单位S",
      "G=1/R：电阻支路电导，单位S",
      "L、C：理想并联电感与电容，分别为H、F；ω单位rad/s",
      "ω0：谐振角频率，单位rad/s；Z(ω0)：谐振时输入阻抗，单位Ω",
    ],
    source: "第5版§11-4（本节始于p.290），按同一参考方向整理",
  },
  {
    name: "对称三相相量和",
    latex: "\\dot U_A+\\dot U_B+\\dot U_C=0",
    position: [12, 1, 1],
    slug: "three-phase-basics",
    condition: "同频、等幅，相位依次相差120°。",
    parameters: [
      "U̇A、U̇B、U̇C：三相电压有效值相量，单位V",
      "A、B、C标记三相；相量和为0并不是各相有效值相加为0",
    ],
    source: "第5版 p.302，§12-1",
  },
  {
    name: "Y连接线值与相值",
    latex: "U_l=\\sqrt3U_p,\\quad I_l=I_p",
    position: [12, 2, 1],
    slug: "line-phase",
    condition: "电压√3关系要求对称；正序线电压超前对应相电压30°。",
    parameters: [
      "Ul、Up：线电压、相电压有效值，单位V；l表示line，p表示phase",
      "Il、Ip：线电流、相电流有效值，单位A",
      "Y中每相负载与对应端线串联，所以Il=Ip；√3电压关系要求对称",
    ],
    source: "第5版式（12-1）的有效值关系",
  },
  {
    name: "Δ连接线值与相值",
    latex: "U_l=U_p,\\quad I_l=\\sqrt3I_p",
    position: [12, 2, 2],
    slug: "line-phase",
    condition: "电流√3关系要求对称；正序线电流滞后对应相电流30°。",
    parameters: [
      "Ul、Up：线电压、相电压有效值，单位V；l为线量，p为相量大小",
      "Il、Ip：线电流、相支路电流有效值，单位A",
      "Δ每相跨接两端线，所以Ul=Up；√3电流关系要求对称",
    ],
    source: "第5版式（12-2）的有效值关系",
  },
  {
    name: "三相一相计算法",
    latex: "\\dot I_A=\\frac{\\dot U_A}{Z+Z_l}",
    position: [12, 3, 1],
    slug: "balanced-three-phase",
    condition: "对称Y-Y；其他连接方式先做适当等效。",
    parameters: [
      "U̇A：电源A相对电源中性点的相电压相量，单位V",
      "İA：A线电流相量，单位A",
      "Z：每相等效Y负载阻抗，单位Ω；Zl：每根端线的线路阻抗，单位Ω",
      "负载是Δ时，先用ZΔ/3换为等效Y再使用此式",
    ],
    source: "第5版 p.306，§12-3",
  },
  {
    name: "中性点位移",
    latex:
      "\\dot U_{N'N}=\\frac{\\dot U_A Y_A+\\dot U_B Y_B+\\dot U_C Y_C}{Y_A+Y_B+Y_C}",
    position: [12, 4, 1],
    slug: "unbalanced-three-phase",
    condition: "Y负载中性线断开，忽略线路阻抗。",
    parameters: [
      "U̇N′N：负载中性点N′相对电源中性点N的电压相量，单位V",
      "U̇A、U̇B、U̇C：电源各相对N的电压相量，单位V",
      "YA、YB、YC：负载各相导纳，单位S；Yk=1/Zk",
      "该式对应中性线断开并忽略线路阻抗的Y负载",
    ],
    source: "第5版 p.309，§12-4",
  },
  {
    name: "三相有功功率",
    latex: "P=\\sqrt3U_lI_l\\cos\\phi",
    position: [12, 5, 1],
    slug: "three-phase-power",
    condition: "对称正弦三相；φ为相电压与相电流的相位差。",
    parameters: [
      "P：三相总有功功率，单位W，不是每相功率",
      "Ul、Il：负载端线电压与线电流有效值，分别为V、A",
      "φ：负载相电压与相电流的相位差，即负载阻抗角；不是线电压与线电流间任意夹角",
    ],
    source: "第5版 p.311–312",
  },
];

export const formulas: FormulaEntry[] = formulaEntries.sort(
  (a, b) =>
    a.position[0] - b.position[0] ||
    a.position[1] - b.position[1] ||
    a.position[2] - b.position[2],
);
