export type FormulaEntry = {
  name: string;
  latex: string;
  position: readonly [chapter: number, section: number, sequence: number];
  supplemental?: boolean;
  slug: string;
  condition: string;
  parameters: string[];
  source: string;
};
const formulaEntries: FormulaEntry[] = [
  {
    name: "耦合因数",
    latex: "k=\\frac{M}{\\sqrt{L_1L_2}}\\leq1",
    position: [10, 1, 1],
    slug: "coupled-inductors",
    condition: "线性、无源的两耦合线圈，M取非负互感大小，0≤k≤1。",
    parameters: ["M、L1、L2：互感与自感 / H", "k：耦合因数，无量纲"],
    source: "第5版p.255，§10-1",
  },
  {
    name: "欧姆定律",
    latex: "u=Ri",
    position: [1, 5, 1],
    slug: "kcl-kvl",
    condition: "线性电阻，电压电流取关联参考方向。",
    parameters: ["u：电压 / V", "i：电流 / A", "R：电阻 / Ω"],
    source: "第5版 p.13，式（1-3）",
  },
  {
    name: "瞬时功率",
    latex: "p=ui",
    position: [1, 3, 1],
    slug: "kcl-kvl",
    condition: "采用关联参考方向；p>0表示吸收功率，p<0表示发出功率。",
    parameters: ["p：瞬时功率 / W", "u：电压 / V", "i：电流 / A"],
    source: "第5版 p.11，§1-3",
  },
  {
    name: "基尔霍夫电流定律",
    latex: "\\sum i=0",
    position: [1, 8, 1],
    slug: "kcl-kvl",
    condition: "集总电路节点，流入与流出符号相反。",
    parameters: ["i：支路电流 / A"],
    source: "第5版 p.21，§1-8",
  },
  {
    name: "电容伏安关系",
    latex: "i=C\\frac{du}{dt}",
    position: [6, 1, 1],
    slug: "capacitor",
    condition: "理想线性电容，关联参考方向。",
    parameters: [
      "C：电容 / F",
      "u：瞬时电压 / V",
      "i：瞬时电流 / A",
      "t：时间 / s",
    ],
    source: "第5版 p.126，式（6-2）",
  },
  {
    name: "电容储能",
    latex: "W_C(t)=\\frac12 Cu^2(t)",
    position: [6, 1, 2],
    slug: "capacitor",
    condition: "理想线性电容。",
    parameters: ["WC：能量 / J", "C：电容 / F", "u(t)：电压 / V"],
    source: "第5版 p.128，式（6-8）",
  },
  {
    name: "RC 时间常数",
    latex: "\\tau=RC",
    position: [7, 2, 1],
    slug: "rc-circuit",
    condition: "R 为电容端口看到的等效电阻，R>0。",
    parameters: ["τ：时间常数 / s", "R：等效电阻 / Ω", "C：电容 / F"],
    source: "第5版 p.141，§7-2",
  },
  {
    name: "电感伏安关系",
    latex: "u=L\\frac{di}{dt}",
    position: [6, 2, 1],
    slug: "inductor",
    condition: "理想线性电感，关联参考方向。",
    parameters: [
      "L：电感 / H",
      "i：瞬时电流 / A",
      "u：瞬时电压 / V",
      "t：时间 / s",
    ],
    source: "第5版 p.130，式（6-11）",
  },
  {
    name: "电感储能",
    latex: "W_L(t)=\\frac12 Li^2(t)",
    position: [6, 2, 2],
    slug: "inductor",
    condition: "理想线性电感。",
    parameters: ["WL：能量 / J", "L：电感 / H", "i(t)：电流 / A"],
    source: "第5版 p.130，式（6-16）的电流形式",
  },
  {
    name: "电阻阻抗",
    latex: "Z_R=R",
    position: [9, 1, 1],
    slug: "impedance",
    condition: "理想电阻，同频正弦稳态。",
    parameters: ["Z：阻抗 / Ω", "R：电阻 / Ω"],
    source: "第5版 p.223，§9-1",
  },
  {
    name: "电感阻抗",
    latex: "Z_L=j\\omega L",
    position: [9, 1, 2],
    slug: "impedance",
    condition: "理想电感，同频正弦稳态。",
    parameters: ["ω：角频率 / rad·s⁻¹", "L：电感 / H", "j：虚数单位"],
    source: "第5版 p.223，§9-1",
  },
  {
    name: "电容阻抗",
    latex: "Z_C=-j\\frac1{\\omega C}",
    position: [9, 1, 3],
    slug: "impedance",
    condition: "理想电容，ω>0，同频正弦稳态。",
    parameters: ["ω：角频率 / rad·s⁻¹", "C：电容 / F", "j：虚数单位"],
    source: "第5版 p.223，§9-1",
  },
  {
    name: "有功功率",
    latex: "P=UI\\cos\\phi_Z",
    position: [9, 4, 1],
    slug: "power",
    condition: "U、I 使用有效值，同频正弦稳态。",
    parameters: [
      "P：有功功率 / W",
      "φZ：电压相位减电流相位",
      "U：有效电压 / V",
      "I：有效电流 / A",
    ],
    source: "第5版 p.235，§9-4",
  },
  {
    name: "对称星三角变换",
    latex: "R_\\Delta=3R_Y",
    position: [2, 4, 2],
    slug: "star-delta",
    condition: "三个电阻相等；保持三个外部端子等效。",
    parameters: ["RΔ：每边三角形电阻 / Ω", "RY：每支星形电阻 / Ω"],
    source: "第5版 p.39，§2-4",
  },
  {
    name: "三角形转星形",
    latex: "R_1=\\frac{R_{12}R_{31}}{R_{12}+R_{23}+R_{31}}",
    position: [2, 4, 1],
    slug: "star-delta",
    condition: "端子1相邻的两条Δ电阻相乘，再除以三边之和。",
    parameters: ["R₁：星形端子1支路 / Ω", "R₁₂、R₂₃、R₃₁：Δ各边 / Ω"],
    source: "第5版式（2-8）",
  },
  {
    name: "对称三相相量和",
    latex: "\\dot U_A+\\dot U_B+\\dot U_C=0",
    position: [12, 1, 1],
    slug: "three-phase-basics",
    condition: "同频、等幅，相位依次相差120°。",
    parameters: ["U̇A、U̇B、U̇C：三相电压相量 / V"],
    source: "第5版 p.302，§12-1",
  },
  {
    name: "Y连接线值与相值",
    latex: "U_l=\\sqrt3U_p,\\quad I_l=I_p",
    position: [12, 2, 1],
    slug: "line-phase",
    condition: "电压√3关系要求对称；正序线电压超前对应相电压30°。",
    parameters: ["Uₗ、Iₗ：线有效值 / V、A", "Uₚ、Iₚ：相有效值 / V、A"],
    source: "第5版式（12-1）的有效值关系",
  },
  {
    name: "Δ连接线值与相值",
    latex: "U_l=U_p,\\quad I_l=\\sqrt3I_p",
    position: [12, 2, 2],
    slug: "line-phase",
    condition: "电流√3关系要求对称；正序线电流滞后对应相电流30°。",
    parameters: ["Uₗ、Iₗ：线有效值 / V、A", "Uₚ、Iₚ：相有效值 / V、A"],
    source: "第5版式（12-2）的有效值关系",
  },
  {
    name: "三相一相计算法",
    latex: "\\dot I_A=\\frac{\\dot U_A}{Z+Z_l}",
    position: [12, 3, 1],
    slug: "balanced-three-phase",
    condition: "对称Y-Y；其他连接方式先做适当等效。",
    parameters: [
      "U̇A：电源相电压 / V",
      "Z：Y相负载阻抗 / Ω",
      "Zₗ：线路阻抗 / Ω",
    ],
    source: "第5版 p.306，§12-3",
  },
  {
    name: "三相有功功率",
    latex: "P=\\sqrt3U_lI_l\\cos\\phi",
    position: [12, 5, 1],
    slug: "three-phase-power",
    condition: "对称正弦三相；φ为相电压与相电流的相位差。",
    parameters: [
      "P：总有功功率 / W",
      "Uₗ、Iₗ：线有效值 / V、A",
      "φ：负载阻抗角",
    ],
    source: "第5版 p.311–312",
  },
  {
    name: "中性点位移",
    latex:
      "\\dot U_{N'N}=\\frac{\\dot U_A Y_A+\\dot U_B Y_B+\\dot U_C Y_C}{Y_A+Y_B+Y_C}",
    position: [12, 4, 1],
    slug: "unbalanced-three-phase",
    condition: "Y负载中性线断开，忽略线路阻抗。",
    parameters: ["Y：每相负载导纳 / S", "U̇N′N：负载中性点电压 / V"],
    source: "第5版 p.309，§12-4",
  },
  {
    name: "电源等效变换",
    latex: "I_S=\\frac{U_S}{R},\\quad U_S=RI_S",
    position: [2, 6, 1],
    slug: "source-transformations",
    condition: "电压源串联R与电流源并联R的完整二端组合；方向由负端指向正端。",
    parameters: ["US：电压源 / V", "IS：电流源 / A", "R：保留的电阻 / Ω"],
    source: "第5版式（2-11）的电阻形式",
  },
  {
    name: "输入电阻测试源法",
    latex: "R_{in}=\\frac{u_t}{i_t}",
    position: [2, 7, 1],
    slug: "thevenin",
    condition: "独立源置零、受控源保留；it取流入网络正端。",
    parameters: ["ut：测试电压 / V", "it：测试电流 / A", "Rin：输入电阻 / Ω"],
    source: "第5版式（2-12）",
  },
  {
    name: "开路短路求等效电阻",
    latex: "R_{eq}=\\frac{u_{oc}}{i_{sc}}",
    position: [4, 3, 1],
    slug: "thevenin",
    condition: "线性一端口；isc有限且非零，按对应端口方向取代数值。",
    parameters: ["uoc：开路电压 / V", "isc：短路电流 / A", "Req：等效电阻 / Ω"],
    source: "第5版式（4-5）",
  },
  {
    name: "叠加的功率交叉项",
    latex: "p=R(i'+i'')^2",
    position: [4, 1, 1],
    slug: "superposition",
    condition: "先叠加同一电阻中的分电流再求功率，不能仅加两个分功率。",
    parameters: ["i′、i″：分电流 / A", "p：总响应下功率 / W", "R：电阻 / Ω"],
    source: "由第5版p.85的功率限制展开",
  },
  {
    name: "桥臂一端口开路电压",
    latex: "u_{oc}=U_S+I_SR",
    supplemental: true,
    position: [2, 7, 2],
    slug: "bridge-arm",
    condition: "仅对应本站图中US左正右负、IS从X指向A的拓扑和方向。",
    parameters: [
      "uoc：A对B开路电压 / V",
      "US：下方电压源 / V",
      "IS：上方电流源 / A",
      "R：并联电阻 / Ω",
    ],
    source: "原创拓扑，由KCL/KVL推得",
  },
  {
    name: "电阻功率",
    latex: "p=Ri^2=\\frac{u^2}{R}",
    position: [1, 5, 2],
    slug: "kcl-kvl",
    condition: "线性电阻，电压电流取关联参考方向。",
    parameters: ["p：功率 / W", "R：电阻 / Ω", "u：电压 / V", "i：电流 / A"],
    source: "第5版p.15，式（1-5）",
  },
  {
    name: "基尔霍夫电压定律",
    latex: "\\sum u=0",
    position: [1, 8, 2],
    slug: "kcl-kvl",
    condition: "集总电路的闭合回路，沿统一绕行方向取电压代数值。",
    parameters: ["u：支路电压 / V"],
    source: "第5版p.22，§1-8",
  },
  {
    name: "双网孔方程",
    latex:
      "\\begin{aligned}(R_1+R_2)i_{m1}-R_2i_{m2}&=u_{S1}-u_{S2}\\\\-R_2i_{m1}+(R_2+R_3)i_{m2}&=u_{S2}-u_{S3}\\end{aligned}",
    position: [3, 4, 1],
    slug: "mesh-analysis",
    condition:
      "对应教材图3-9，两网孔均按教材方向；公共支路电流为网孔电流之差。",
    parameters: [
      "R1、R2、R3：各支路电阻 / Ω",
      "im1、im2：网孔电流 / A",
      "uS1、uS2、uS3：支路电源电压 / V",
    ],
    source: "第5版p.61–62，式（3-6）",
  },
  {
    name: "结点电压方程（第一行）",
    latex: "G_{11}u_{n1}+G_{12}u_{n2}+G_{13}u_{n3}=i_{S11}",
    position: [3, 6, 1],
    slug: "nodal-analysis",
    condition: "教材三独立结点方程的第一行；自导为正，互导为负。",
    parameters: [
      "G：电导 / S",
      "un：结点电压 / V",
      "iS11：流入结点1的电流源代数和 / A",
    ],
    source: "第5版p.70，式（3-18）的第一行",
  },
  {
    name: "相量对应的瞬时量",
    latex: "u=\\sqrt2 U\\cos(\\omega t+\\phi_u)",
    position: [8, 3, 1],
    slug: "phasor",
    condition: "余弦参考，U使用有效值；瞬时量与相量是对应关系。",
    parameters: [
      "u：瞬时电压 / V",
      "U：有效值 / V",
      "ω：角频率 / rad·s⁻¹",
      "φu：初相位",
    ],
    source: "第5版p.209，§8-3",
  },
  {
    name: "有效值相量",
    latex: "\\dot U=Ue^{j\\phi_u}=U\\angle\\phi_u",
    position: [8, 3, 2],
    slug: "phasor",
    condition: "同频正弦稳态、余弦参考；U使用有效值。",
    parameters: [
      "U̇：电压相量 / V",
      "U：有效值 / V",
      "φu：初相位",
      "j：虚数单位",
    ],
    source: "第5版p.210，§8-3",
  },
  {
    name: "RLC串联阻抗",
    latex: "Z(j\\omega)=R+j\\left(\\omega L-\\frac1{\\omega C}\\right)",
    position: [11, 2, 1],
    slug: "rlc",
    condition: "理想R、L、C串联，R>0，ω>0。",
    parameters: [
      "Z：输入阻抗 / Ω",
      "R：电阻 / Ω",
      "L：电感 / H",
      "C：电容 / F",
    ],
    source: "第5版p.281，§11-2",
  },
  {
    name: "RLC串联谐振频率",
    latex: "\\omega_0=\\frac1{\\sqrt{LC}},\\qquad f_0=\\frac1{2\\pi\\sqrt{LC}}",
    position: [11, 2, 2],
    slug: "rlc",
    condition: "理想串联RLC，谐振时感抗与容抗相等。",
    parameters: [
      "ω0：谐振角频率 / rad·s⁻¹",
      "f0：谐振频率 / Hz",
      "L：电感 / H",
      "C：电容 / F",
    ],
    source: "第5版p.282，§11-2",
  },
  {
    name: "电流和电压的参考方向关系",
    latex: "i=\\frac{\\mathrm dq}{\\mathrm dt},\\qquad u_{ab}=v_a-v_b",
    position: [1, 2, 20],
    slug: "chapter-1-summary",
    condition:
      "电流方向和电压极性是人为规定的参考。先规定方向，计算结果为负才表示实际方向相反。电流进入电压正端称关联参考方向，用它统一元件功率和伏安关系。",
    parameters: [
      "q：电荷 / C",
      "t：时间 / s",
      "u、U：电压 / V",
      "i、I：电流 / A",
    ],
    source: "第5版§1-2（本节始于p.9），按同一参考方向整理",
  },
  {
    name: "电压源和电流源关系",
    latex: "u=U_S\\quad\\text{或}\\quad i=I_S",
    position: [1, 6, 20],
    slug: "chapter-1-summary",
    condition:
      "理想电压源约束端电压，其电流由外电路决定；理想电流源约束电流，其端电压由外电路决定。电压源置零等效短路，电流源置零等效开路。受约束量与未约束量必须分清。",
    parameters: [
      "q：电荷 / C",
      "t：时间 / s",
      "u、U：电压 / V",
      "i、I：电流 / A",
    ],
    source: "第5版§1-6（本节始于p.16），按同一参考方向整理",
  },
  {
    name: "电阻的串联和并联关系",
    latex:
      "R_s=\\sum R_k,\\quad G_p=\\sum G_k,\\quad u_k=\\frac{R_k}{R_s}u,\\quad i_k=\\frac{G_k}{G_p}i",
    position: [2, 3, 20],
    slug: "chapter-2-summary",
    condition:
      "串联元件流过同一电流，并联元件跨在同一对结点。串联分压按电阻成正比，并联分流按电导成正比；两支路分流也可用对侧电阻写比例。",
    parameters: [
      "R：电阻 / Ω",
      "G：电导 / S",
      "u、U：电压 / V",
      "i、I：电流 / A",
    ],
    source: "第5版§2-3（本节始于p.33），按同一参考方向整理",
  },
  {
    name: "电压源、电流源的串联和并联关系",
    latex: "U_{eq}=\\sum U_{Sk},\\qquad I_{eq}=\\sum I_{Sk}",
    position: [2, 5, 20],
    slug: "chapter-2-summary",
    condition:
      "串联电压源的电压按极性相加，并联电流源的电流按方向相加。理想电压源并联必须电压一致，理想电流源串联必须电流一致，否则约束矛盾。源的未约束量由外部电路决定。",
    parameters: [
      "R：电阻 / Ω",
      "G：电导 / S",
      "u、U：电压 / V",
      "i、I：电流 / A",
    ],
    source: "第5版§2-5（本节始于p.41），按同一参考方向整理",
  },
  {
    name: "电路的图关系",
    latex: "b_t=n-1,\\qquad b_l=b-n+1",
    position: [3, 1, 20],
    slug: "chapter-3-summary",
    condition:
      "图保留结点和支路的连接关系，忽略元件形状与参数。树是包含全部结点而不形成回路的连通子图，非树支路是连支。支路划分可按元件或串联组合，但结点与支路数要同步。",
    parameters: [
      "b：支路数，无量纲",
      "n：结点数，无量纲",
      "i：电流 / A",
      "u：电压 / V",
      "R：电阻 / Ω",
    ],
    source: "第5版§3-1（本节始于p.52），按同一参考方向整理",
  },
  {
    name: "KCL和KVL的独立方程数关系",
    latex: "N_{KCL}=n-1,\\quad N_{KVL}=b-n+1",
    position: [3, 2, 20],
    slug: "chapter-3-summary",
    condition:
      "连通网络的独立KCL方程数为n−1，独立KVL方程数为b−n+1，两者合计b。其余结点或回路方程能由它们线性组合得到。方程独立性与元件参数无关。",
    parameters: [
      "b：支路数，无量纲",
      "n：结点数，无量纲",
      "i：电流 / A",
      "u：电压 / V",
      "R：电阻 / Ω",
    ],
    source: "第5版§3-2（本节始于p.54），按同一参考方向整理",
  },
  {
    name: "支路电流法关系",
    latex: "i_1-i_2-i_3=0,\\quad R_1i_1+R_2i_2=U_S,\\quad R_2i_2=R_3i_3",
    position: [3, 3, 20],
    slug: "chapter-3-summary",
    condition:
      "以各支路电流为未知量，写n−1个KCL，再用元件关系把b−n+1个KVL写成电流方程。方法通用但未知量往往较多，适合结构简单、支路电流本身是目标的题目。",
    parameters: [
      "b：支路数，无量纲",
      "n：结点数，无量纲",
      "i：电流 / A",
      "u：电压 / V",
      "R：电阻 / Ω",
    ],
    source: "第5版§3-3（本节始于p.58），按同一参考方向整理",
  },
  {
    name: "回路电流法关系",
    latex:
      "i_k=\\sum_{m=1}^{b-n+1}\\sigma_{km}i_{lm},\\qquad \\sigma_{km}\\in\\{-1,0,1\\}",
    position: [3, 5, 20],
    slug: "chapter-3-summary",
    condition:
      "回路法适用于一般连通网络。选一棵树，每加入一条连支形成一个基本回路，令其回路电流与该连支方向一致；树支电流是多个回路电流的代数和。网孔法是平面网络的一种便利选择。",
    parameters: [
      "b：支路数，无量纲",
      "n：结点数，无量纲",
      "i：电流 / A",
      "u：电压 / V",
      "R：电阻 / Ω",
    ],
    source: "第5版§3-5（本节始于p.64），按同一参考方向整理",
  },
  {
    name: "替代定理关系",
    latex: "u_S=u_p\\quad\\text{或}\\quad i_S=i_p",
    position: [4, 2, 20],
    slug: "chapter-4-summary",
    condition:
      "已知某二端子部分的端电压和电流，可用相同电压的理想电压源或相同电流的理想电流源替代，在原工作状态下保持其余网络的电压电流。要保证替代后解存在且唯一。它不等于对任意负载都成立的端口等效。",
    parameters: [
      "u、U：电压 / V",
      "i、I：电流 / A",
      "R：电阻 / Ω",
      "P：功率 / W",
    ],
    source: "第5版§4-2（本节始于p.88），按同一参考方向整理",
  },
  {
    name: "最大功率传输定理关系",
    latex: "R_L=R_{eq},\\qquad P_{max}=\\frac{u_{oc}^2}{4R_{eq}}",
    position: [4, 4, 20],
    slug: "chapter-4-summary",
    condition:
      "对固定的线性直流戴维南源，若Req>0且可调负载是正电阻，RL=Req时负载获得最大功率。这里优化的是负载功率，不是效率；负载变化时要保持源侧等效参数不变。",
    parameters: [
      "u、U：电压 / V",
      "i、I：电流 / A",
      "R：电阻 / Ω",
      "P：功率 / W",
    ],
    source: "第5版§4-4（本节始于p.97），按同一参考方向整理",
  },
  {
    name: "电容、电感元件的串联与并联关系",
    latex:
      "C_p=\\sum C_k,\\quad\\frac1{C_s}=\\sum\\frac1{C_k},\\quad L_s=\\sum L_k,\\quad\\frac1{L_p}=\\sum\\frac1{L_k}",
    position: [6, 3, 20],
    slug: "chapter-6-summary",
    condition:
      "并联电容电压相同，电容值相加；串联电容按倒数相加。无互感的串联电感电流相同，电感值相加；并联电感按倒数相加。初始储能与电荷约束仍要另外保留。",
    parameters: ["C：电容 / F", "L：电感 / H"],
    source: "第5版§6-3（本节始于p.131），按同一参考方向整理",
  },
  {
    name: "动态电路的方程及其初始条件关系",
    latex:
      "u_C(0_+)=u_C(0_-),\\quad i_L(0_+)=i_L(0_-),\\quad RC\\frac{\\mathrm du_C}{\\mathrm dt}+u_C=U_S",
    position: [7, 1, 20],
    slug: "chapter-7-summary",
    condition:
      "本学习范围只考虑一阶电路。换路前直流稳态用电容开路、电感短路求初值；换路后先用电容电压、电感电流连续性，再通过KCL/KVL求其余瞬时量。切换后的等效网络决定响应，不沿用旧网络的时间常数。",
    parameters: [
      "u、U：电压 / V",
      "i、I：电流 / A",
      "R：等效电阻 / Ω",
      "L：电感 / H",
      "C：电容 / F",
      "t、τ：时间 / s",
    ],
    source: "第5版§7-1（本节始于p.137），按同一参考方向整理",
  },
  {
    name: "一阶电路的零状态响应关系",
    latex:
      "u_C(t)=U_S(1-e^{-t/\\tau}),\\qquad i_L(t)=\\frac{U_S}{R}(1-e^{-t/\\tau})",
    position: [7, 3, 20],
    slug: "chapter-7-summary",
    condition:
      "零状态表示初始电容电压或电感电流为0，响应仅由外部激励引起。本页只讨论t=0接入恒定直流源后的普通充电、建流，不展开阶跃或冲激专题。初始值为0不等于响应一直为0。",
    parameters: [
      "u、U：电压 / V",
      "i、I：电流 / A",
      "R：等效电阻 / Ω",
      "L：电感 / H",
      "C：电容 / F",
      "t、τ：时间 / s",
    ],
    source: "第5版§7-3（本节始于p.147），按同一参考方向整理",
  },
  {
    name: "一阶电路的全响应关系",
    latex: "f(t)=f(\\infty)+[f(0_+)-f(\\infty)]e^{-t/\\tau}",
    position: [7, 4, 20],
    slug: "chapter-7-summary",
    condition:
      "全响应同时包含初始储能与外部激励。三要素是0+初值、∞终值和时间常数；也可写为零输入加零状态，或稳态分量加暂态分量。两种分解角度不同，零输入不等于暂态的同义词。",
    parameters: [
      "u、U：电压 / V",
      "i、I：电流 / A",
      "R：等效电阻 / Ω",
      "L：电感 / H",
      "C：电容 / F",
      "t、τ：时间 / s",
    ],
    source: "第5版§7-4（本节始于p.152），按同一参考方向整理",
  },
  {
    name: "正弦量关系",
    latex:
      "u=U_m\\cos(\\omega t+\\phi),\\quad U=\\frac{U_m}{\\sqrt2},\\quad\\omega=2\\pi f,\\quad T=\\frac1f",
    position: [8, 2, 20],
    slug: "chapter-8-summary",
    condition:
      "正弦量由峰值、角频率和初相位决定。有效值用于同频正弦功率和有效值相量。先把sin改为共同的cos参考，再提取初相位；相位超前通常对应波形向左移动。不同频率的两量不能用一个固定相位差描述。",
    parameters: [
      "U、Um：电压有效值、峰值 / V",
      "I：电流有效值 / A",
      "ω：角频率 / rad·s⁻¹",
      "f：频率 / Hz",
      "T：周期 / s",
      "φ：初相位",
    ],
    source: "第5版§8-2（本节始于p.205），按同一参考方向整理",
  },
  {
    name: "电路定律的相量形式关系",
    latex:
      "\\sum\\dot I=0,\\quad\\sum\\dot U=0,\\quad\\dot U_R=R\\dot I,\\quad\\dot U_L=j\\omega L\\dot I,\\quad\\dot U_C=\\frac{\\dot I}{j\\omega C}",
    position: [8, 4, 20],
    slug: "chapter-8-summary",
    condition:
      "在同频线性正弦稳态中，KCL、KVL仍成立，但变量换成相量；R、L、C的伏安关系分别对应R、jωL、1/(jωC)。电感电压超前电流90°，电容电压滞后电流90°。",
    parameters: [
      "U、Um：电压有效值、峰值 / V",
      "I：电流有效值 / A",
      "ω：角频率 / rad·s⁻¹",
      "f：频率 / Hz",
      "T：周期 / s",
      "φ：初相位",
    ],
    source: "第5版§8-4（本节始于p.211），按同一参考方向整理",
  },
  {
    name: "电路的相量图关系",
    latex: "\\dot U=\\dot U_R+\\dot U_L+\\dot U_C",
    position: [9, 2, 20],
    slug: "chapter-9-summary",
    condition:
      "相量图是复数方程的几何表示。串联取共同电流作参考，并联取共同电压作参考。等量纲相量按同一比例尺首尾相接，最终起点到终点的箭头为总量。相量可平移，不能随意改变长度或方向。",
    parameters: [
      "U、I：有效值 / V、A",
      "Z：阻抗 / Ω",
      "P、Q、S：有功、无功、视在功率 / W、var、VA",
      "XL、XC：电抗大小 / Ω",
    ],
    source: "第5版§9-2（本节始于p.226），按同一参考方向整理",
  },
  {
    name: "复功率关系",
    latex: "\\overline S=\\dot U\\dot I^*=P+jQ,\\qquad S=\\sqrt{P^2+Q^2}",
    position: [9, 5, 20],
    slug: "chapter-9-summary",
    condition:
      "关联方向下复功率为电压相量乘电流相量共轭，实部为P、虚部为Q，其模为S。复功率可按支路相加，但不同支路视在功率的大小不能一般直接相加。复功率不是电压电流的同频相量。",
    parameters: [
      "U、I：有效值 / V、A",
      "Z：阻抗 / Ω",
      "P、Q、S：有功、无功、视在功率 / W、var、VA",
      "XL、XC：电抗大小 / Ω",
    ],
    source: "第5版§9-5（本节始于p.238），按同一参考方向整理",
  },
  {
    name: "最大功率传输关系",
    latex:
      "Z_L=Z_{eq}^*,\\quad P_{max}=\\frac{U_{oc}^2}{4R_{eq}};\\qquad X_L=0:\\ R_L=|Z_{eq}|",
    position: [9, 6, 20],
    slug: "chapter-9-summary",
    condition:
      "固定频率下把源侧化为Uoc与Zeq=Req+jXeq。若负载R、X均可调且Req>0，最佳负载是共轭匹配；若只能调纯电阻，最佳RL是源阻抗的模。约束不同，结论不同。",
    parameters: [
      "U、I：有效值 / V、A",
      "Z：阻抗 / Ω",
      "P、Q、S：有功、无功、视在功率 / W、var、VA",
      "XL、XC：电抗大小 / Ω",
    ],
    source: "第5版§9-6（本节始于p.241），按同一参考方向整理",
  },
  {
    name: "含有耦合电感电路的计算关系",
    latex:
      "L_{eq}=L_1+L_2\\pm2M,\\quad\\dot U_1=j\\omega L_1\\dot I_1\\pm j\\omega M\\dot I_2",
    position: [10, 2, 20],
    slug: "chapter-10-summary",
    condition:
      "互感项将两支路方程耦合，不能把每个线圈独立当作jωL处理。串联同向时等效电感L1+L2+2M，反向时L1+L2−2M；更一般的网络要按同名端写联立相量方程。",
    parameters: [
      "L1、L2、M：自感与互感 / H",
      "i、I：电流 / A",
      "u、U：电压 / V",
      "ω：角频率 / rad·s⁻¹",
      "n：匝比，无量纲",
      "Z：阻抗 / Ω",
      "W：储能 / J",
    ],
    source: "第5版§10-2（本节始于p.257），按同一参考方向整理",
  },
  {
    name: "耦合电感的功率关系",
    latex: "W=\\frac12L_1i_1^2+\\frac12L_2i_2^2\\pm Mi_1i_2",
    position: [10, 3, 20],
    slug: "chapter-10-summary",
    condition:
      "无损耦合电感通过磁场交换能量，总瞬时端口功率等于磁场储能变化率。互感储能项带符号，但无源模型的总能量不能任意为负；正弦稳态下可以在两个端口间传递有功。",
    parameters: [
      "L1、L2、M：自感与互感 / H",
      "i、I：电流 / A",
      "u、U：电压 / V",
      "ω：角频率 / rad·s⁻¹",
      "n：匝比，无量纲",
      "Z：阻抗 / Ω",
      "W：储能 / J",
    ],
    source: "第5版§10-3（本节始于p.262），按同一参考方向整理",
  },
  {
    name: "变压器原理关系",
    latex:
      "(R_1+j\\omega L_1)\\dot I_1+j\\omega M\\dot I_2=\\dot U_1,\\quad j\\omega M\\dot I_1+(R_2+j\\omega L_2+Z_L)\\dot I_2=0",
    position: [10, 4, 20],
    slug: "chapter-10-summary",
    condition:
      "实际变压器用耦合线圈描述，绕组电阻带来铜耗，漏磁使k小于1，磁化支路需要电流。一次、二次回路通过互阻抗jωM联系。负载会反映到一次侧，开路、短路状态要区分。",
    parameters: [
      "L1、L2、M：自感与互感 / H",
      "i、I：电流 / A",
      "u、U：电压 / V",
      "ω：角频率 / rad·s⁻¹",
      "n：匝比，无量纲",
      "Z：阻抗 / Ω",
      "W：储能 / J",
    ],
    source: "第5版§10-4（本节始于p.265），按同一参考方向整理",
  },
  {
    name: "理想变压器关系",
    latex:
      "\\frac{\\dot U_1}{\\dot U_2}=n,\\quad\\dot I_1=-\\frac{\\dot I_2}{n},\\quad Z_{in}=n^2Z_L",
    position: [10, 5, 20],
    slug: "chapter-10-summary",
    condition:
      "理想模型忽略损耗、漏磁与有限磁化电流，用匝比n=N1/N2规定电压和电流约束。两侧电流均流入同名端时电流比带负号；负载电流采用输出方向时符号相应改变。",
    parameters: [
      "L1、L2、M：自感与互感 / H",
      "i、I：电流 / A",
      "u、U：电压 / V",
      "ω：角频率 / rad·s⁻¹",
      "n：匝比，无量纲",
      "Z：阻抗 / Ω",
      "W：储能 / J",
    ],
    source: "第5版§10-5（本节始于p.268），按同一参考方向整理",
  },
  {
    name: "RLC并联谐振电路关系",
    latex:
      "Y=G+j\\left(\\omega C-\\frac1{\\omega L}\\right),\\quad\\omega_0=\\frac1{\\sqrt{LC}},\\quad Z(\\omega_0)=\\frac1G",
    position: [11, 4, 20],
    slug: "chapter-11-summary",
    condition:
      "本节采用教材G、L、C并联模型。谐振条件是总导纳虚部为0，感性支路与容性支路电流相互抵消。固定端电压下电源电流最小，输入阻抗最大为1/G，支路电流仍可很大。",
    parameters: [
      "G：电导 / S",
      "L：电感 / H",
      "C：电容 / F",
      "ω：角频率 / rad·s⁻¹",
      "Z：阻抗 / Ω",
    ],
    source: "第5版§11-4（本节始于p.290），按同一参考方向整理",
  },
  {
    name: "RL 时间常数",
    latex: "\\tau=\\frac{L}{R_{eq}}",
    position: [7, 2, 2],
    slug: "rl-circuit",
    condition: "R为电感端口看到的等效电阻，Req>0；独立源置零、受控关系保留。",
    parameters: ["τ：时间常数 / s", "L：电感 / H", "Req：等效电阻 / Ω"],
    source: "第5版p.144，§7-2",
  },
  {
    name: "RL 零输入响应",
    latex: "i_L(t)=I_0e^{-t/\\tau}",
    position: [7, 2, 3],
    slug: "rl-circuit",
    condition: "无外部独立激励，由初始电感储能产生的一阶响应，τ=L/Req。",
    parameters: ["iL、I0：电流 / A", "t、τ：时间 / s"],
    source: "第5版§7-2，p.144",
  },
  {
    name: "欧拉公式",
    latex: "e^{j\\theta}=\\cos\\theta+j\\sin\\theta",
    position: [8, 1, 1],
    slug: "complex-euler",
    condition: "指数中的角使用弧度，j²=−1。",
    parameters: ["θ：角 / rad", "j：虚数单位，无量纲"],
    source: "第5版§8-1，p.202–204的同一数学关系",
  },
  {
    name: "余弦的指数形式",
    latex: "\\cos\\theta=\\frac{e^{j\\theta}+e^{-j\\theta}}2",
    position: [8, 1, 2],
    slug: "complex-euler",
    condition: "指数中的角使用弧度，j²=−1。",
    parameters: ["θ：角 / rad", "j：虚数单位，无量纲"],
    source: "第5版§8-1，p.202–204的同一数学关系",
  },
  {
    name: "正弦的指数形式",
    latex: "\\sin\\theta=\\frac{e^{j\\theta}-e^{-j\\theta}}{2j}",
    position: [8, 1, 3],
    slug: "complex-euler",
    condition: "指数中的角使用弧度，j²=−1。",
    parameters: ["θ：角 / rad", "j：虚数单位，无量纲"],
    source: "第5版§8-1，p.202–204的同一数学关系",
  },
  {
    name: "功率因数",
    latex: "\\lambda=\\cos\\phi_Z=\\frac{P}{S}",
    position: [9, 4, 2],
    slug: "power-factor",
    condition: "同频正弦条件；含谐波时不能仅用相位差余弦。",
    parameters: ["λ：功率因数，无量纲", "P：有功功率 / W", "S：视在功率 / VA"],
    source: "第5版p.236，§9-4",
  },
  {
    name: "并联电容补偿",
    latex: "C=\\frac{P(\\tan\\phi_1-\\tan\\phi_2)}{\\omega U^2}",
    position: [9, 4, 3],
    slug: "power-factor",
    condition: "理想正弦单相并联补偿，电压保持不变。",
    parameters: [
      "C：补偿电容 / F",
      "P：有功功率 / W",
      "ω：角频率 / rad·s⁻¹",
      "U：有效电压 / V",
      "φ1、φ2：补偿前后电源侧功率因数角",
    ],
    source: "第5版p.241，等价写法",
  },
];

export const formulas: FormulaEntry[] = formulaEntries.sort(
  (a, b) =>
    a.position[0] - b.position[0] ||
    a.position[1] - b.position[1] ||
    a.position[2] - b.position[2],
);
