export type FormulaEntry = {
  name: string;
  latex: string;
  category: string;
  slug: string;
  condition: string;
  parameters: string[];
  source: string;
};
export const formulas: FormulaEntry[] = [
  {
    name: "欧姆定律",
    latex: "u=Ri",
    category: "基础电路",
    slug: "kcl-kvl",
    condition: "线性电阻，电压电流取关联参考方向。",
    parameters: ["u：电压 / V", "i：电流 / A", "R：电阻 / Ω"],
    source: "第5版 p.13，式（1-3）",
  },
  {
    name: "电功率",
    latex: "p=ui=Ri^2=\\frac{u^2}{R}",
    category: "基础电路",
    slug: "kcl-kvl",
    condition: "后两式仅用于电阻；p=ui 采用关联参考方向。",
    parameters: [
      "p：瞬时功率 / W",
      "u：电压 / V",
      "i：电流 / A",
      "R：电阻 / Ω",
    ],
    source: "第5版 p.15，式（1-5）",
  },
  {
    name: "基尔霍夫电流定律",
    latex: "\\sum i=0",
    category: "基础电路",
    slug: "kcl-kvl",
    condition: "集总电路节点，流入与流出符号相反。",
    parameters: ["i：支路电流 / A"],
    source: "第5版 p.21，§1-8",
  },
  {
    name: "电容伏安关系",
    latex: "i=C\\frac{du}{dt}",
    category: "电容",
    slug: "capacitor",
    condition: "理想线性电容，关联参考方向。",
    parameters: [
      "C：电容 / F",
      "u：瞬时电压 / V",
      "i：瞬时电流 / A",
      "t：时间 / s",
    ],
    source: "第5版 p.126，式（6-2）",
  },
  {
    name: "电容储能",
    latex: "W_C(t)=\\frac12 Cu^2(t)",
    category: "电容",
    slug: "capacitor",
    condition: "理想线性电容。",
    parameters: ["WC：能量 / J", "C：电容 / F", "u(t)：电压 / V"],
    source: "第5版 p.128，式（6-8）",
  },
  {
    name: "RC 时间常数",
    latex: "\\tau=RC",
    category: "电容",
    slug: "rc-circuit",
    condition: "R 为电容端口看到的等效电阻，R>0。",
    parameters: ["τ：时间常数 / s", "R：等效电阻 / Ω", "C：电容 / F"],
    source: "第5版 p.141，§7-2",
  },
  {
    name: "电感伏安关系",
    latex: "u=L\\frac{di}{dt}",
    category: "电感",
    slug: "inductor",
    condition: "理想线性电感，关联参考方向。",
    parameters: [
      "L：电感 / H",
      "i：瞬时电流 / A",
      "u：瞬时电压 / V",
      "t：时间 / s",
    ],
    source: "第5版 p.130，式（6-11）",
  },
  {
    name: "电感储能",
    latex: "W_L(t)=\\frac12 Li^2(t)",
    category: "电感",
    slug: "inductor",
    condition: "理想线性电感。",
    parameters: ["WL：能量 / J", "L：电感 / H", "i(t)：电流 / A"],
    source: "第5版 p.130，式（6-16）的电流形式",
  },
  {
    name: "电阻阻抗",
    latex: "Z_R=R",
    category: "正弦稳态",
    slug: "impedance",
    condition: "理想电阻，同频正弦稳态。",
    parameters: ["Z：阻抗 / Ω", "R：电阻 / Ω"],
    source: "第5版 p.223，§9-1",
  },
  {
    name: "电感阻抗",
    latex: "Z_L=j\\omega L",
    category: "正弦稳态",
    slug: "impedance",
    condition: "理想电感，同频正弦稳态。",
    parameters: ["ω：角频率 / rad·s⁻¹", "L：电感 / H", "j：虚数单位"],
    source: "第5版 p.223，§9-1",
  },
  {
    name: "电容阻抗",
    latex: "Z_C=-j\\frac1{\\omega C}",
    category: "正弦稳态",
    slug: "impedance",
    condition: "理想电容，ω>0，同频正弦稳态。",
    parameters: ["ω：角频率 / rad·s⁻¹", "C：电容 / F", "j：虚数单位"],
    source: "第5版 p.223，§9-1",
  },
  {
    name: "有功功率",
    latex: "P=UI\\cos\\phi_Z",
    category: "正弦稳态",
    slug: "power",
    condition: "U、I 使用有效值，同频正弦稳态。",
    parameters: [
      "P：有功功率 / W",
      "φZ：电压相位减电流相位",
      "U：有效电压 / V",
      "I：有效电流 / A",
    ],
    source: "第5版 p.235，§9-4",
  },
  {
    name: "对称星三角变换",
    latex: "R_\\Delta=3R_Y",
    category: "基础电路",
    slug: "star-delta",
    condition: "三个电阻相等；保持三个外部端子等效。",
    parameters: ["RΔ：每边三角形电阻 / Ω", "RY：每支星形电阻 / Ω"],
    source: "第5版 p.39，§2-4",
  },
  {
    name: "三角形转星形",
    latex: "R_1=\\frac{R_{12}R_{31}}{R_{12}+R_{23}+R_{31}}",
    category: "基础电路",
    slug: "star-delta",
    condition: "端子1相邻的两条Δ电阻相乘，再除以三边之和。",
    parameters: ["R₁：星形端子1支路 / Ω", "R₁₂、R₂₃、R₃₁：Δ各边 / Ω"],
    source: "第5版式（2-8）",
  },
  {
    name: "对称三相相量和",
    latex: "\\dot U_A+\\dot U_B+\\dot U_C=0",
    category: "三相电路",
    slug: "three-phase-basics",
    condition: "同频、等幅，相位依次相差120°。",
    parameters: ["U̇A、U̇B、U̇C：三相电压相量 / V"],
    source: "第5版 p.302，§12-1",
  },
  {
    name: "Y连接线值与相值",
    latex: "U_l=\\sqrt3U_p,\\quad I_l=I_p",
    category: "三相电路",
    slug: "line-phase",
    condition: "电压√3关系要求对称；正序线电压超前对应相电压30°。",
    parameters: ["Uₗ、Iₗ：线有效值 / V、A", "Uₚ、Iₚ：相有效值 / V、A"],
    source: "第5版式（12-1）的有效值关系",
  },
  {
    name: "Δ连接线值与相值",
    latex: "U_l=U_p,\\quad I_l=\\sqrt3I_p",
    category: "三相电路",
    slug: "line-phase",
    condition: "电流√3关系要求对称；正序线电流滞后对应相电流30°。",
    parameters: ["Uₗ、Iₗ：线有效值 / V、A", "Uₚ、Iₚ：相有效值 / V、A"],
    source: "第5版式（12-2）的有效值关系",
  },
  {
    name: "三相一相计算法",
    latex: "\\dot I_A=\\frac{\\dot U_A}{Z+Z_l}",
    category: "三相电路",
    slug: "balanced-three-phase",
    condition: "对称Y-Y；其他连接方式先做适当等效。",
    parameters: [
      "U̇A：电源相电压 / V",
      "Z：Y相负载阻抗 / Ω",
      "Zₗ：线路阻抗 / Ω",
    ],
    source: "第5版 p.306，§12-3",
  },
  {
    name: "三相有功功率",
    latex: "P=\\sqrt3U_lI_l\\cos\\phi",
    category: "三相电路",
    slug: "three-phase-power",
    condition: "对称正弦三相；φ为相电压与相电流的相位差。",
    parameters: [
      "P：总有功功率 / W",
      "Uₗ、Iₗ：线有效值 / V、A",
      "φ：负载阻抗角",
    ],
    source: "第5版 p.311–312",
  },
  {
    name: "中性点位移",
    latex:
      "\\dot U_{N'N}=\\frac{\\dot U_A Y_A+\\dot U_B Y_B+\\dot U_C Y_C}{Y_A+Y_B+Y_C}",
    category: "三相电路",
    slug: "unbalanced-three-phase",
    condition: "Y负载中性线断开，忽略线路阻抗。",
    parameters: ["Y：每相负载导纳 / S", "U̇N′N：负载中性点电压 / V"],
    source: "第5版 p.309，§12-4",
  },
  {
    name: "二瓦计法",
    latex: "P=P_1+P_2",
    category: "三相电路",
    slug: "three-phase-power",
    condition: "三相三线制；读数取代数和，不要求负载对称。",
    parameters: ["P：总有功功率 / W", "P₁、P₂：两路读数 / W"],
    source: "第5版 p.311，§12-5",
  },
];
