export type TextbookTopic = {
  chapter: number;
  section: number;
  title: string;
  page: number;
  slug: string;
  anchor: string;
};

export const textbookTopics: readonly TextbookTopic[] = [
  {
    chapter: 1,
    section: 1,
    title: "电路和电路模型",
    page: 7,
    slug: "chapter-1-summary",
    anchor: "textbook-1-1",
  },
  {
    chapter: 1,
    section: 2,
    title: "电流和电压的参考方向",
    page: 9,
    slug: "chapter-1-summary",
    anchor: "textbook-1-2",
  },
  {
    chapter: 1,
    section: 3,
    title: "电功率和能量",
    page: 11,
    slug: "chapter-1-summary",
    anchor: "textbook-1-3",
  },
  {
    chapter: 1,
    section: 4,
    title: "电路元件",
    page: 12,
    slug: "chapter-1-summary",
    anchor: "textbook-1-4",
  },
  {
    chapter: 1,
    section: 5,
    title: "电阻元件",
    page: 13,
    slug: "chapter-1-summary",
    anchor: "textbook-1-5",
  },
  {
    chapter: 1,
    section: 6,
    title: "电压源和电流源",
    page: 16,
    slug: "chapter-1-summary",
    anchor: "textbook-1-6",
  },
  {
    chapter: 1,
    section: 7,
    title: "受控电源",
    page: 18,
    slug: "chapter-1-summary",
    anchor: "textbook-1-7",
  },
  {
    chapter: 1,
    section: 8,
    title: "基尔霍夫定律",
    page: 20,
    slug: "chapter-1-summary",
    anchor: "textbook-1-8",
  },
  {
    chapter: 2,
    section: 1,
    title: "引言",
    page: 32,
    slug: "chapter-2-summary",
    anchor: "textbook-2-1",
  },
  {
    chapter: 2,
    section: 2,
    title: "电路的等效变换",
    page: 32,
    slug: "chapter-2-summary",
    anchor: "textbook-2-2",
  },
  {
    chapter: 2,
    section: 3,
    title: "电阻的串联和并联",
    page: 33,
    slug: "chapter-2-summary",
    anchor: "textbook-2-3",
  },
  {
    chapter: 2,
    section: 4,
    title: "电阻的Y形联结和Δ形联结的等效变换",
    page: 37,
    slug: "chapter-2-summary",
    anchor: "textbook-2-4",
  },
  {
    chapter: 2,
    section: 5,
    title: "电压源、电流源的串联和并联",
    page: 41,
    slug: "chapter-2-summary",
    anchor: "textbook-2-5",
  },
  {
    chapter: 2,
    section: 6,
    title: "实际电源的两种模型及其等效变换",
    page: 42,
    slug: "chapter-2-summary",
    anchor: "textbook-2-6",
  },
  {
    chapter: 2,
    section: 7,
    title: "输入电阻",
    page: 45,
    slug: "chapter-2-summary",
    anchor: "textbook-2-7",
  },
  {
    chapter: 3,
    section: 1,
    title: "电路的图",
    page: 52,
    slug: "chapter-3-summary",
    anchor: "textbook-3-1",
  },
  {
    chapter: 3,
    section: 2,
    title: "KCL和KVL的独立方程数",
    page: 54,
    slug: "chapter-3-summary",
    anchor: "textbook-3-2",
  },
  {
    chapter: 3,
    section: 3,
    title: "支路电流法",
    page: 58,
    slug: "chapter-3-summary",
    anchor: "textbook-3-3",
  },
  {
    chapter: 3,
    section: 4,
    title: "网孔电流法",
    page: 60,
    slug: "chapter-3-summary",
    anchor: "textbook-3-4",
  },
  {
    chapter: 3,
    section: 5,
    title: "回路电流法",
    page: 64,
    slug: "chapter-3-summary",
    anchor: "textbook-3-5",
  },
  {
    chapter: 3,
    section: 6,
    title: "结点电压法",
    page: 69,
    slug: "chapter-3-summary",
    anchor: "textbook-3-6",
  },
  {
    chapter: 4,
    section: 1,
    title: "叠加定理",
    page: 82,
    slug: "chapter-4-summary",
    anchor: "textbook-4-1",
  },
  {
    chapter: 4,
    section: 2,
    title: "替代定理",
    page: 88,
    slug: "chapter-4-summary",
    anchor: "textbook-4-2",
  },
  {
    chapter: 4,
    section: 3,
    title: "戴维宁定理和诺顿定理",
    page: 90,
    slug: "chapter-4-summary",
    anchor: "textbook-4-3",
  },
  {
    chapter: 4,
    section: 4,
    title: "最大功率传输定理",
    page: 97,
    slug: "chapter-4-summary",
    anchor: "textbook-4-4",
  },
  {
    chapter: 6,
    section: 1,
    title: "电容元件",
    page: 126,
    slug: "chapter-6-summary",
    anchor: "textbook-6-1",
  },
  {
    chapter: 6,
    section: 2,
    title: "电感元件",
    page: 129,
    slug: "chapter-6-summary",
    anchor: "textbook-6-2",
  },
  {
    chapter: 6,
    section: 3,
    title: "电容、电感元件的串联与并联",
    page: 131,
    slug: "chapter-6-summary",
    anchor: "textbook-6-3",
  },
  {
    chapter: 7,
    section: 1,
    title: "动态电路的方程及其初始条件",
    page: 137,
    slug: "chapter-7-summary",
    anchor: "textbook-7-1",
  },
  {
    chapter: 7,
    section: 2,
    title: "一阶电路的零输入响应",
    page: 140,
    slug: "chapter-7-summary",
    anchor: "textbook-7-2",
  },
  {
    chapter: 7,
    section: 3,
    title: "一阶电路的零状态响应",
    page: 147,
    slug: "chapter-7-summary",
    anchor: "textbook-7-3",
  },
  {
    chapter: 7,
    section: 4,
    title: "一阶电路的全响应",
    page: 152,
    slug: "chapter-7-summary",
    anchor: "textbook-7-4",
  },
  {
    chapter: 8,
    section: 1,
    title: "复数",
    page: 202,
    slug: "chapter-8-summary",
    anchor: "textbook-8-1",
  },
  {
    chapter: 8,
    section: 2,
    title: "正弦量",
    page: 205,
    slug: "chapter-8-summary",
    anchor: "textbook-8-2",
  },
  {
    chapter: 8,
    section: 3,
    title: "相量法的基础",
    page: 208,
    slug: "chapter-8-summary",
    anchor: "textbook-8-3",
  },
  {
    chapter: 8,
    section: 4,
    title: "电路定律的相量形式",
    page: 211,
    slug: "chapter-8-summary",
    anchor: "textbook-8-4",
  },
  {
    chapter: 9,
    section: 1,
    title: "阻抗和导纳",
    page: 220,
    slug: "chapter-9-summary",
    anchor: "textbook-9-1",
  },
  {
    chapter: 9,
    section: 2,
    title: "电路的相量图",
    page: 226,
    slug: "chapter-9-summary",
    anchor: "textbook-9-2",
  },
  {
    chapter: 9,
    section: 3,
    title: "正弦稳态电路的分析",
    page: 227,
    slug: "chapter-9-summary",
    anchor: "textbook-9-3",
  },
  {
    chapter: 9,
    section: 4,
    title: "正弦稳态电路的功率",
    page: 233,
    slug: "chapter-9-summary",
    anchor: "textbook-9-4",
  },
  {
    chapter: 9,
    section: 5,
    title: "复功率",
    page: 238,
    slug: "chapter-9-summary",
    anchor: "textbook-9-5",
  },
  {
    chapter: 9,
    section: 6,
    title: "最大功率传输",
    page: 241,
    slug: "chapter-9-summary",
    anchor: "textbook-9-6",
  },
  {
    chapter: 10,
    section: 1,
    title: "互感",
    page: 252,
    slug: "chapter-10-summary",
    anchor: "textbook-10-1",
  },
  {
    chapter: 10,
    section: 2,
    title: "含有耦合电感电路的计算",
    page: 257,
    slug: "chapter-10-summary",
    anchor: "textbook-10-2",
  },
  {
    chapter: 10,
    section: 3,
    title: "耦合电感的功率",
    page: 262,
    slug: "chapter-10-summary",
    anchor: "textbook-10-3",
  },
  {
    chapter: 10,
    section: 5,
    title: "理想变压器",
    page: 268,
    slug: "chapter-10-summary",
    anchor: "textbook-10-5",
  },
  {
    chapter: 11,
    section: 2,
    title: "RLC串联电路的谐振",
    page: 281,
    slug: "chapter-11-summary",
    anchor: "textbook-11-2",
  },
  {
    chapter: 11,
    section: 4,
    title: "RLC并联谐振电路",
    page: 290,
    slug: "chapter-11-summary",
    anchor: "textbook-11-4",
  },
  {
    chapter: 12,
    section: 1,
    title: "三相电路",
    page: 301,
    slug: "chapter-12-summary",
    anchor: "textbook-12-1",
  },
  {
    chapter: 12,
    section: 2,
    title: "线电压（电流）与相电压（电流）的关系",
    page: 303,
    slug: "chapter-12-summary",
    anchor: "textbook-12-2",
  },
  {
    chapter: 12,
    section: 3,
    title: "对称三相电路的计算",
    page: 306,
    slug: "chapter-12-summary",
    anchor: "textbook-12-3",
  },
  {
    chapter: 12,
    section: 4,
    title: "不对称三相电路的概念",
    page: 308,
    slug: "chapter-12-summary",
    anchor: "textbook-12-4",
  },
  {
    chapter: 12,
    section: 5,
    title: "三相电路的功率",
    page: 310,
    slug: "chapter-12-summary",
    anchor: "textbook-12-5",
  },
];
